### ISSUE TITLE
Professional space (aka Kohesio Lab)

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#110]
Develop intranet access for REGIO specials and member states correspondents

**Comment by madewild** [comment]
There is the idea to put the Qlik dashboard developed by Catia behind the "Professional Space" button, at least for now.
It's protected by EU Login and there is the Qlik license/token complex scheme so let's discuss with Catia how to do it.

**Comment by raphdom** [comment]
fixed

**Comment by madewild** [comment]
Reopening this as it's unclear if we will keep the (incomplete) qlik dashboard or put something else behind the pro space.
@AThollard mentioned something done by REGIO colleagues using PowerBI...

**Comment by madewild** [comment]
Or link to monitoring tool?

**Comment by madewild** [comment]
If nothing is ready, hide professional space link

**Comment by AThollard** [comment]
Nothing's mature enough for March, so I would say hide for now.
(we should prepare a new version of templates + guidelines for version 1.2)

**Comment by madewild** [comment]
@raphdom can you hide it? then I will move to 1.2 milestone

**Comment by omar0z** [comment]
Should be already hidden in dev.

**Comment by madewild** [comment]
Great! By the way @omar0z could you also hide the language selector? We don't have time to make the site multilingual for the official launch...

**Comment by AThollard** [comment]
Yes, already have a new name idea for that -> Kohesio Lab :-) but first let's launch Kohesio!

**Comment by madewild** [comment]
Mostly implemented by the edit workflow. Let's create separate issues if we need additional features later on.
