### ISSUE TITLE
Autotype in intervention field advanced filter

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#214]
To let the user type and get matches instead of scrolling

**Comment by raphdom** [comment]
to do this, we need to change the component itself to eui-autocomplete, but the problem is that the autocomplete doesn't support subitems, need to check a better way to do it. I ask you to postponed this to another release.

**Comment by madewild** [comment]
OK no problem

**Comment by madewild** [comment]
Possibility to combine autocomplete with tree, allowing to select parent category (e.g. "Productive investment") to retrieve all children?

**Comment by madewild** [comment]
@raphdom do you want to delegate this? or we postpone to 1.1?

**Comment by prototorpedo** [comment]
Created this PR:
https://github.com/ec-doris/kohesio-frontend/pull/557

First issue is that what appears in the input field after selection is the id (I think) of the category. Not sure how to mitigate this.

**Comment by madewild** [comment]
Let's harmonise the spacing:
![spacing](https://user-images.githubusercontent.com/942488/155142842-01f01918-022b-42a8-8cd7-b7dd8c1622b9.png)

- remove the extra space between "intervention field" and "Please select" box
- remove the extra space between "Please select" and "Date"

**Comment by prototorpedo** [comment]
I don't think there's a good fix for this. The space under the input is actually padding and seems to be used for validation messages and animations. Removing it breaks the underline.

**Comment by prototorpedo** [comment]
There are a few other caveats I have noticed with this component:
* When you select an item, the cursor will be positioned at the end of the input. That's expected, but for long texts like we have, you can't really tell what category it is
* When focusing on the input after a selection, you will have the list filtered to that selection only, as that is the value of the input 

What are your thoughts on this @madewild @raphdom

**Comment by madewild** [comment]
Indeed...

- for the first point you just have to click anywhere outside the box to make the cursor go to the beginning, good enough for now
- the other is a bit more annoying since not behaving like other filters... you have to click "Reset filters" to get the full list again
@raphdom any quick fix? if not we can leave like that and improve for 1.2
@roberto-musmeci can you test?

**Comment by madewild** [comment]
@prototorpedo your change https://github.com/ec-doris/kohesio-frontend/commit/33e4cd0b1d88eb42fd33651afcac97ecfa249607 fixed the display but broke the autotype functionality! It's not working anymore (check https://kohesio.development.ec.europa.eu/projects) since that commit (I checked it out in detached head to confirm it's the guilty commit...)

**Comment by prototorpedo** [comment]
huh...I'll check it but it should have worked...

**Comment by madewild** [comment]
Works now!
