### ISSUE TITLE
Localisation in 24 EU official languages

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#22]
When we get the contents...

**Comment by D063520** [comment]
About this .... for the search, map, beneficiary page .... in the APIs there should be always a language parameter .... if the knowledge is present in the knowledge base the only thing you need to do is to set it to "fr"

**Comment by madewild** [comment]
One option is to try new eTranslation widget.

This comes with a disclaimer, cf. https://ec.europa.eu/info/departments/translation/language-industry-platform-lind

**Comment by madewild** [comment]
Probably easier with localization module from eUI to have more control

**Comment by madewild** [comment]
This will come back sooner or later... let's try to anticipate :)

**Comment by D063520** [comment]
NOTE: a lot of this vocabulary

<img width="297" alt="Screenshot 2021-05-06 at 13 17 26" src="https://user-images.githubusercontent.com/10883585/117289873-6d19ae80-ae6d-11eb-8b7a-e2cd7281153c.png">

Can be extracted form the Knowledge Graph too.

**Comment by madewild** [comment]
This will impact (semantic) search: each localized version should search on content in the same language

**Comment by madewild** [comment]
@raphdom what do you think is realistic here in terms of timeline? we could start with adding French and/or German then add all 24 languages... it also implies running eTranslation on all projects

**Comment by madewild** [comment]
Mission for January: evaluate the workload on UI side, explore possibilities using DGT (human) translators...

**Comment by madewild** [comment]
@raphdom generate a json/csv static file with all strings to translate
@madewild check what data in the wikibase should be humanly translated

**Comment by D063520** [comment]
Note that some things are already for example for :
<img width="292" alt="Screenshot 2021-12-20 at 10 27 04" src="https://user-images.githubusercontent.com/10883585/146744450-c7d068eb-96b0-41a5-bfe0-9050ee6e5046.png">
we have
<img width="1118" alt="Screenshot 2021-12-20 at 10 28 31" src="https://user-images.githubusercontent.com/10883585/146744510-dd68ef85-75e9-455b-880f-509dfd04c31e.png">

I would prefer to have this all in the Knowledge Base. For example for project we can reuse Wikidata data:

https://linkedopendata.eu/wiki/Item:Q196788

**Comment by madewild** [comment]
Yes of course, we will do it as much as possible in the wikibase.
But some strings like "Project Information Portal for Regional Policy" etc are specific to the website only.

Try with one or two languages? (French and/or German?)
If languages are not ready, hide language selector link

**Comment by D063520** [comment]
Hi Max,

a few comments:

- translate all other Wikibase contents (countries, regions, themes, intervention fields, etc.) 
      -> I would take the country names/regions from wikidata or maybe check some vocabulary from eurostats
      -> intervention fields are already translated https://linkedopendata.eu/wiki/Item:Q200734 (we took them from the files provided by thierry)
- Index all data in Elasticsearch in all languages, and allow to search by language (not mixing them up, separate indices!)
      -> we should not index in ES otherwise the current search will not work. We have prepared this. Here the pull requests we made agains rdf4j to achieve this

https://github.com/eclipse/rdf4j/pull/3727
https://github.com/eclipse/rdf4j/pull/3731 

- Remove hardcoded strings from frontend code, replacing by keys: the front-end should take the keys from the backend too. We have some translations like here 
     ->  https://linkedopendata.eu/wiki/Property:P888

**Comment by madewild** [comment]
I agree we should use the backend when possible but we will still have things like "Curious to discover what Europe does in your region?" or "Projects near me" or "Contact the Kohesio Team" etc. We will not put everything in the Wikibase...
