### ISSUE TITLE
Update about page

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#222]
Add extra disclaimer (see with @slaven777 and @bisiaam)
Remove explicit mention to 6 countries and replace by "added on a continuous basis)

**Comment by madewild** [comment]
@gachpas could you coordinate this?

**Comment by gachpas** [comment]
Hello @madewild, @AThollard will coordinate this with Slaven ;)

**Comment by AThollard** [comment]
@madewild thanks
For the OP project of linked data initiative map we also have to review Kohesio description.
So I would kill two birds with one stone and review the description and about with @slaven777 and @Bisiaam 
[LOD comm_KOHESIO_Project Owner Questionnaire.docx](https://github.com/ec-doris/kohesio.eu/files/6695374/LOD.comm_KOHESIO_Project.Owner.Questionnaire.docx)
[Diagram and graphic example.pdf](https://github.com/ec-doris/kohesio.eu/files/6695377/Diagram.and.graphic.example.pdf)

**Comment by madewild** [comment]
@AThollard where do we stand with this?

**Comment by AThollard** [comment]
> @AThollard where do we stand with this?

I have received contribution from Slaven and Amaury. I am currently reviewing it together with the OP questionnaire.
What is your deadline for the next release?

**Comment by madewild** [comment]
we want to deploy next Monday, so would be good to have it on Thusday...

**Comment by AThollard** [comment]
ok, well noted

**Comment by madewild** [comment]
also add banner

**Comment by raphdom** [comment]
the new about page and the banner are available in DEV, can you test please? @AThollard @madewild

**Comment by madewild** [comment]
ABOUT Kohesio.eu > About kohesio.eu
missing space between "developmentand"

**Comment by raphdom** [comment]
fixed

**Comment by madewild** [comment]
I see the extra space, but I would also change the heading "ABOUT Kohesio.eu" into "About kohesio.eu"
Also, I would write  CNECT-ECDORIS@ec.europa.eu in full like for REGIO-KM

**Comment by madewild** [comment]
The link is missing behing Wikimedia Deutschland: https://wikimedia.de/

**Comment by raphdom** [comment]
all fixed

**Comment by madewild** [comment]
Looks good to me, I let @AThollard @gachpas comment before closing

**Comment by AThollard** [comment]
ok for me for the About section.

**Comment by madewild** [comment]
comment from @gachpas : why give 2 email addresses to report translation errors?
I agree, we could put just the EC-DORIS one there and specify the REGIO-KM for more generic questions about Kohesio
@AThollard do you agree? we can discuss the exact wording to give to @raphdom

**Comment by AThollard** [comment]
> comment from @gachpas : why give 2 email addresses to report translation errors?
> I agree, we could put just the EC-DORIS one there and specify the REGIO-KM for more generic questions about Kohesio
> @AThollard do you agree? we can discuss the exact wording to give to @raphdom

I agree, please  let EC-DORIS for translation issues. And maybe we could put just a Contact mention at the end of the About page with REGIO-KM.

**Comment by madewild** [comment]
Contact
For any enquiry about Kohesio, please contact REGIO-KM@ec.europa.eu.

**Comment by D063520** [comment]
Maybe we should add something similar as the translation also for 
- the geo-coordinates: done using nominatim (https://nominatim.openstreetmap.org/ui/search.html)
- benficiary linking: done using ML
-(these are the 2 steps that we do to enrich the data)

**Comment by AThollard** [comment]
> Maybe we should add something similar as the translation also for
> 
> * the geo-coordinates: done using nominatim (https://nominatim.openstreetmap.org/ui/search.html)
> * benficiary linking: done using ML
>   -(these are the 2 steps that we do to enrich the data)

what about adding the next release?
I don't want to enter into the full reviewing process today :-(

**Comment by madewild** [comment]
I created a new issue for this (https://github.com/ec-doris/kohesio.eu/issues/233) so that we can close this one.

**Comment by madewild** [comment]
All done on https://dev.kohesio.eu/about

**Comment by madewild** [comment]
@roberto-musmeci let's follow up here on the changes needed for the About page

**Comment by madewild** [comment]
Hi @madewild, "[About](https://eceuropaeu.sharepoint.com/:w:/r/sites/GRP-REGIOKMteam/Shared%20Documents/Kohesio%20Com%20-%20presentations/About%20-%20FAQ/Kohesio%20about.docx?d=wbed9d140df524e339636860c808e6b89&csf=1&web=1&e=BbZfnx)" amended version ready in Teams

[Kohesio about.docx](https://github.com/ec-doris/kohesio-frontend/files/8115240/Kohesio.about.docx)

FYI: @gachpas @roberto-musmeci

_Originally posted by @AThollard in https://github.com/ec-doris/kohesio-frontend/issues/461

**Comment by AThollard** [comment]
Fine with me. I can't even spot your changes ;-)

**Comment by madewild** [comment]
All the datasets are available both in CSV/XLSX and in RDF format (see [Services page](https://kohesio.development.ec.europa.eu/services)). ;)

**Comment by gachpas** [comment]
@madewild , 

d'un point devue grammatical, je pense que, dans la première section du About, il faudrait corriger "It aims to correct imbalances between countries and regions" en "It aims at correcting imbalances between countries and regions"
Br, Pascal

**Comment by madewild** [comment]
done on dev
