### ISSUE TITLE
Mobile version - issue for "playing" with the map

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#245]
it is difficult and not too much reactive to navigate through the map by resizing

PS: test done with Iphone7 and safari

**Comment by madewild** [comment]
@gachpas you need 2 fingers to resize AND move the map, to avoid issues with the rest of the navigation on mobile...
can we close ou could you give an example of another site where it works better?

**Comment by madewild** [comment]
@gachpas @Bisiaam @D063520 could you explain more specifically what the problem?

**Comment by gachpas** [comment]
@madewild , not so easy to put in words the user experience..I will try to ;)
A first concrete (and easy to expalin) element is the fact that the breadcrumb is hiding part of th emap and therefore projects points.
Another element is that sometime there is a delay  of some miliseconds between th emoment you use the 2 fingers to enlarge or zoom in into th emap. This latency is difficult to manage while trying to use the map.
It does not seem to be linked to internet connections but like it was slow in recalculating...

I hope that the comment is a bit more concrete now? :)

**Comment by Bisiaam** [comment]
> @gachpas you need 2 fingers to resize AND move the map, to avoid issues with the rest of the navigation on mobile... can we close ou could you give an example of another site where it works better?

For me it's a bit difficult to move the map with 2 fingers, it doesn't work all the time

**Comment by raphdom** [comment]
We can postponed the interaction with the map on mobile to the next release as we will have some main changes specially when we apply the ECL look and feel

**Comment by raphdom** [comment]
Finally we are back in this issue. I've updated the plugin to interact with the map on mobile, I've test on my iphone and seems quite good. Can you test it @gachpas and @madewild ? on dev, today in the end of the day we are going to send it to test environment.

**Comment by madewild** [comment]
Cool, @AThollard @roberto-musmeci @Bisiaam could you also test?

**Comment by gachpas** [comment]
@raphdom, it is indeed better. ;) Thx

**Comment by roberto-musmeci** [comment]
Navigation seems ok to me. 

One issue is that if you open a circle with several projects, the tooltip appears and if you try to scroll down the map displays "use two fingers to move in the map". The list items still scroll down on the background but it is not ideal.

**Comment by madewild** [comment]
@raphdom can we do something about this?

**Comment by Bisiaam** [comment]
I tested it. I agree with Roberto, otherwise all good with me :)

**Comment by raphdom** [comment]
not easy this one, but fixed. Now we have the version on test with all changes also. Can you test it to finally close this issue? @madewild @Bisiaam @roberto-musmeci @gachpas

**Comment by madewild** [comment]
I tested on Fairphone3/Android and works perfectly! :)
