### ISSUE TITLE
Create a FAQ

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#261]
Based on @AThollard request (if still needed)

**Comment by madewild** [comment]
Maybe add in this faq that interreg is not yet covered + a link to keep.eu

**Comment by AThollard** [comment]
@slaven777 @Bisiaam @roberto-musmeci  Could you please prepare a draft FAQ getting inspiration from https://ec.europa.eu/regional_policy/en/faq/about_open_data/
Most obvious ones for me:
What is Cohesion Policy? (link to https://ec.europa.eu/regional_policy/en/policy/what/investment-policy/)
Who provides the data?
Which funds are covered in Kohesio?
Can I download the datasets
What is a Knowledge graph?
(good one ;-)
What's the difference between Kohesio and Cohesiondata?
How can I reuse the data?
Do you plan to add other data sources / funds in the Future?
Which tool do you use for Kohesio?
...

**Comment by roberto-musmeci** [comment]
Starting the work on that

**Comment by madewild** [comment]
OK, let me know if we need to postpone to 1.1

**Comment by AThollard** [comment]
@gachpas could you please coordinate this pls? and see for when we would be able to deliver.
Thnks

**Comment by gachpas** [comment]
Hello @madewild and @raphdom ,
Slaven will provide the FAQ content by 21/02/2022.
Could you please plan for some space in your busy planning for adding the content on Kohesio around that date?
Thanks and kr,
Pascal
cc: @AThollard

**Comment by madewild** [comment]
OK we wait for the contents and then @prototorpedo will implement it for release 1.1

**Comment by madewild** [comment]
Add info about download button and exports:

- download specific search results limited to 5000 for performance reasons (button displayed only if number <= 5000)
- go to https://kohesio.ec.europa.eu/data to access full exports of projects and beneficiaries by country

**Comment by madewild** [comment]
Page ready on https://kohesio.development.ec.europa.eu/faq
Waiting for the contents :)

**Comment by gachpas** [comment]
Hello @slaven777 and @roberto-musmeci , 
here is teh place for FAQ. 
Agreed deadline is 21/02 ;)
Br,
Pascal

**Comment by Bisiaam** [comment]
yes we're on it :)

**Comment by AThollard** [comment]
@madewild first version of FAQ page ready
[Kohesio FAQ_rev1_final.docx](https://github.com/ec-doris/kohesio-frontend/files/8115262/Kohesio.FAQ_rev1_final.docx)
Also in [Teams](https://eceuropaeu.sharepoint.com/:w:/s/GRP-REGIOKMteam/EV9HLAUUhYlEmUgojuim4UgBE0tyAGB2eFo3zetrceJcGA?e=q3OiQM)
FYI: @roberto-musmeci @gachpas

**Comment by madewild** [comment]
I will try to integrate this before @raphdom merges to ACC...

**Comment by madewild** [comment]
FAQ is available on https://kohesio.development.ec.europa.eu/faq
@AThollard @Bisiaam @roberto-musmeci @gachpas can you test?

**Comment by roberto-musmeci** [comment]
works perfectly both on laptop and mobile! Thanks Max, we can close it :)

**Comment by AThollard** [comment]
It is fine, thanks.
There is a wrong link in the section "Can I download the datasets?"
It is also possible to access the complete exports of projects and beneficiaries by country by clicking on [this link](https://kohesio.development.ec.europa.eu/data). it leads to a blank page. @roberto-musmeci can you take care of that?
@madewild finally do we have the page with 'services' somewhere? we should link it from this section  "Can I download the datasets?"of the FAQ?

**Comment by roberto-musmeci** [comment]
> It is fine, thanks. There is a wrong link in the section "Can I download the datasets?" It is also possible to access the complete exports of projects and beneficiaries by country by clicking on [this link](https://kohesio.development.ec.europa.eu/data). it leads to a blank page. @roberto-musmeci can you take care of that? @madewild finally do we have the page with 'services' somewhere? we should link it from this section "Can I download the datasets?"of the FAQ?

I think that the download page is work in progress since the same link exists in this page 
https://kohesio.development.ec.europa.eu/services

**Comment by madewild** [comment]
@AThollard it is not a wrong link, it's just that we don't have any /data in DEV with the live index
in TEST it works: https://kohesio.test.ec.europa.eu/data/ (but still needs improvement, cf. https://github.com/ec-doris/kohesio-frontend/issues/548

**Comment by AThollard** [comment]
Ok, sorry, fine with me then.
