### ISSUE TITLE
Improve thumbnails

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#266]
Some big pictures like https://linkedopendata.eu/w/images/1/1d/CF.10.134_Rehabilitation_of_the_former_landfill_at_Wied_Fulija-15_rs.jpg are not rendered properly in smaller versions: https://dev.kohesio.eu/projects/Q3064384

It's a bit compressed and stretched... Let's see what we can do.

**Comment by madewild** [comment]
not so bad here...
@roberto-musmeci do you have examples where it's very bad? if not we close ;)

**Comment by roberto-musmeci** [comment]
On my browser, images in all nubnails are squized rather then cropped. the problem is more visible in the project result list rather than on the project fishe. Anyway, it is not a big deal so up to you to decide. 
for example https://kohesio.eu/projects/Q139588

![image](https://user-images.githubusercontent.com/86654885/146752654-71240a90-16ce-4a55-adde-15a1527ea931.png)

![image](https://user-images.githubusercontent.com/86654885/146752755-a2e66c7c-add1-4d89-9ac1-f4598b362eb5.png)

**Comment by madewild** [comment]
@raphdom is there an easy solution to crop instead of squeezing/strectching? feel free to re-assign...

**Comment by prototorpedo** [comment]
Using background-image with background-size: cover on the div offers a slight improvement, but just for that one photo. Not sure if it's worth it or if this fix has some drawbacks?

**Comment by madewild** [comment]
OK, let's try to find a generic solution and not something too custom... You can test with other images as well:

https://dev.kohesio.eu/projects/Q139958
https://dev.kohesio.eu/projects/Q141625
https://dev.kohesio.eu/projects/Q192825
etc.

**Comment by prototorpedo** [comment]
It's not custom at all. Actually the other solution I proposed is not as good...I went for divs with background-image and background-size: cover.

**Comment by madewild** [comment]
OK then I musunderstood "offers a slight improvement, but just for that one photo" ;)

**Comment by prototorpedo** [comment]
I didn't test enough photos when I said it 😃 a lot of them are actually displaying better. My concern for this is to not affect SEO by mot using images, but I don't know too much about that

**Comment by madewild** [comment]
@prototorpedo I don't see the image improvement on https://kohesio.development.ec.europa.eu/projects/Q139588 ... can you check?

**Comment by madewild** [comment]
(ah on https://kohesio.development.ec.europa.eu/projects/Q139958 it's nice :) )

**Comment by madewild** [comment]
@roberto-musmeci if you want to check make sure to clean the cache ;)

**Comment by madewild** [comment]
It looks like this did not survive the ECL move...
https://kohesio.development.ec.europa.eu/projects/Q139958
https://kohesio.development.ec.europa.eu/projects/Q107810
@prototorpedo can you check?

**Comment by prototorpedo** [comment]
It doesn't appear that the code made it there at all

**Comment by madewild** [comment]
Yeah so it's a side effect... can you please retrieve the proper code and integrate it in the ECL version? thx
