### ISSUE TITLE
Audiovisual material

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#269]
Currently we have only images and no videos/sounds so the term "audiovisual" sounds strange to me.
Moreover, we have multiple spellings:

- the tab is called "Audio-visual" with a dash (and for me this is an adjective without a noun)
- when no ressources it reads "NO AUDIO VISUAL ASSETS FOUND!" (with a space, also the capitals are a bit aggressive and I would write "audiovisual material" rather than assets)
- on the project detail page it's currently hidden but will come back

@AThollard @gachpas @roberto-musmeci to decide for final version

**Comment by AThollard** [comment]
- Tab spelling: Audiovisual (videos will come at some point)
- when no resource: "No audiovisual material available"
- we should make this available on the project detail page again now that we have more content. Also maybe add the link to InfoRegio when exists with an 'additional information' link

**Comment by madewild** [comment]
@raphdom can you take care of this?

**Comment by madewild** [comment]
@svili the first two changes are cosmetic
the third one already exists, we should uncomment in the code when we have something to show

**Comment by svili** [comment]
The first two changes are fine, but for the third one:
How can I know if there are related materials for the project and to where should a link point to? The backend doesnt seem to provide such information.

**Comment by madewild** [comment]
I think you need to call the image API: https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/project/image?offset=0&limit=15
but does this api allow to query on one project only? @D063520 @DiaZork ?

**Comment by svili** [comment]
#325 only added the box but not the links, will come back to it later just wanted to push out a bunch of other changes.

**Comment by madewild** [comment]
@svili could you remove the allcaps and the exclamation mark? I find it a bit aggressive ;)

NO AUDIOVISUAL MATERIAL AVAILABLE! -> No audiovisual material available

And on the project fiche:

Related materials > Audiovisual material
"Images & Videos" + "Communication campaign" can be removed
I propose we just add the images from the api under the heading "Audiovisual material"

**Comment by madewild** [comment]
Almost there: https://dev.kohesio.eu/projects/Q139577
@AThollard @gachpas can you have a look and comment on it?
@svili will fix the strange right padding

**Comment by madewild** [comment]
Also @svili : could you hide the "Audiovisual material" heading when there is nothing to show?
Looks weird on https://dev.kohesio.eu/projects/Q3097484 for instance...

**Comment by gachpas** [comment]
@madewild , I had understood that Anne wanted to see "No Audiovisual material available" when there is nothing...so not clear to me why deleting the heading? Why not keeping the heading and adding that sentence in case theer is nothing?
Br

**Comment by madewild** [comment]
OK for me but we will have this sentence for almost all projects then... @AThollard let us know before @svili does the change.

**Comment by AThollard** [comment]
Thanks @gachpas and @madewild 
I wanted to keep the heading 'audiovisual material' because I had in mind to put systematic link to InfoRegio when it exists.
Now that we have put the link elsewhere in the project info, you can remove the heading. And of course remove it only when we don't have audiovisual material.

**Comment by AThollard** [comment]
@madewild @gachpas @svili 
I have just looked closer at the final result when we display the images under the 'audiovisual material heading and for me it does not fly. Look at this one for example: [https://dev.kohesio.eu/projects/Q192825],  even for cow lovers:-/
Then 2 options, pick the simpler one for you:
- We replace the image as such by a link to the image as initially planned and if possible. This way we will be able to enrich with other links (videos, communication campaigns and so on)
- We remove totally this heading and content for version 1.1 and wait for more content to display.
cc: @Bisiaam @slaven

**Comment by madewild** [comment]
Well clicking on the thumbnail above is already a link to the same image... Except if we have several images for the same project.

I propose we discuss this on Friday and take a final decision for this release.

**Comment by madewild** [comment]
Thank you for small cow lovers :)

**Comment by AThollard** [comment]
Thanks @svili and sorry for big and small cow lovers, but I think we should get rid of the images and the audiovisual heading for the time being. Or create a serious game: "Cowhesio": find the cow related projects :-D
Ok sorry, let's discuss tomorrow.

**Comment by madewild** [comment]
So @svili let's hide the whole section again, and then I postpone to 1.2 to discuss calmly which links to include etc.

**Comment by madewild** [comment]
@gachpas can you coordinate this after the launch and provide requirements of what we want to achieve exactly? thx

**Comment by gachpas** [comment]
hello @madewild , no problem. What would be the new deadline for you to have the final requirements? Thx
Pascal

**Comment by madewild** [comment]
1.2 is for June so would be good to have the reqs around mid-April or May at the lastest :)

**Comment by madewild** [comment]
I suggest postponing this to 1.3

**Comment by madewild** [comment]
@AThollard @gachpas is still still something we want for 1.3? If yes we would need more specifics...

**Comment by Bisiaam** [comment]
I know that @roberto-musmeci found 254 new projects thanks to his algorithm, but now we have to confirm them manually and in order to help us we need a comparison table. Otherwise, it will take too much time.

**Comment by madewild** [comment]
@D063520 we need to add the video url property to the project detail API

**Comment by roberto-musmeci** [comment]
potential good ECL component is the gallery  
https://ec.europa.eu/component-library/ec/components/media/gallery/usage/

**Comment by D063520** [comment]
@roberto-musmeci please provide an example

**Comment by madewild** [comment]
Try auto-disappearing pop-up "Select a subregion to see individual projects"

**Comment by roberto-musmeci** [comment]
> @roberto-musmeci please provide an example

property is https://linkedopendata.eu/wiki/Property:P2210 

project example: https://kohesio.test.ec.europa.eu/en/projects/Q4110492

**Comment by madewild** [comment]
In the graph: https://linkedopendata.eu/wiki/Item:Q4110492

**Comment by D063520** [comment]
<img width="1728" alt="Screenshot 2022-09-07 at 11 25 40" src="https://user-images.githubusercontent.com/10883585/188843156-0f89dc96-ecc9-4761-b651-a5602035a4cd.png">
is done
https://kohesio.development.ec.europa.eu/en/projects/Q4110492

**Comment by madewild** [comment]
I think so in the first phase... we can add more media type later on.

**Comment by D063520** [comment]
there are 2 different properties, one is youtube and the other one is video in the KB. Just as an information

**Comment by D063520** [comment]
video looks cool, I would somehow put it above the map ....

**Comment by D063520** [comment]
it's a bit strange that the page is in english but the video is in italian (sorry, very picky complaining)

**Comment by madewild** [comment]
Not convinced about that because we have maps for all projects but only video for 500...

**Comment by raphdom** [comment]
@D063520 can you give me an example with the other video in KB, as you said?

**Comment by D063520** [comment]
Hi Raph, the other property is not used currently. So I would close this issue until we do not find an example ...
