### ISSUE TITLE
Embedding maps

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#276]
Some countries ask about embedding Kohesio maps in their own websites.
From what I understand, this would require an api like https://www.embed-leaflet.com/ but with multiple markers and then generating an iframe snippet. Any other option?

**Comment by madewild** [comment]
Let's explore a first simple version for 1.3
Caution: how to provide support for implementation?!

**Comment by madewild** [comment]
@raphdom did you have the time to look into this? Not urgent, just to get an idea of what is achievable later on...

**Comment by raphdom** [comment]
I put the last parameter for this version:
https://kohesio.development.ec.europa.eu/en/map?heatScale=true
I think we can close this and open new issues when is need to improve this feature.

**Comment by raphdom** [comment]
@madewild ?
