### ISSUE TITLE
Hide names of non-EU country on the map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#318]
Check if GISCO provides a layer with only the names of EU countries?

**Comment by raphdom** [comment]
They have indeed, only with EU countries:
<img width="1267" alt="Screenshot 2022-02-02 at 08 59 26" src="https://user-images.githubusercontent.com/5124917/152115272-ea01e5b2-0d2f-47d1-b490-a4a4e8ba509b.png">

But the regions and all other names is not available in this version:
<img width="1259" alt="Screenshot 2022-02-02 at 08 59 48" src="https://user-images.githubusercontent.com/5124917/152115342-a6e96c91-3f47-4cb0-b518-716f3441af6a.png">

Let me know if this version is better, we could add the regions names when we zoom in in each country.

**Comment by madewild** [comment]
@AThollard @gachpas what would be better in your opinion?

**Comment by AThollard** [comment]
@madewild @gachpas can we discuss this briefly so I am sure to understand the options

**Comment by madewild** [comment]
@raphdom let's implement the new one without regions at Europe level, but add the regions (switch layer) when we zoom on one country

**Comment by AThollard** [comment]
@madewild clear now, thanks! as discussed please implement the map with the EU country name (extended) only.

**Comment by raphdom** [comment]
@madewild @AThollard it was implemented, of course that will be a lot of discussion about the label, the positioning, but it is not easy to have a default rule to position label for each region, it is not a layer in the map, it is me that create a marker in the center of the region, but. sometimes the label is huge and cannot fit.

**Comment by madewild** [comment]
Indeed this is quite ugly compared to the previous version... whu do we have this strange bold font and background grey box?

**Comment by madewild** [comment]
@AThollard maybe we should contact the GISCO colleague again and ask if there is another layer we can use...

**Comment by madewild** [comment]
P.S. available options on https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?spaceKey=webtools&title=Map+-+Available+tile+services

**Comment by raphdom** [comment]
The country names is part of the layer, I cannot do much about this or maybe they have something to change the look and feel, but it is not exposed in the API documentation (link above). The regions label is on my control (font-size, color).

**Comment by madewild** [comment]
So @raphdom let's revert for now and then I postpone the issue to 1.2.
I will contact GISCO + the REGIO GIS team to find a better solution.

**Comment by raphdom** [comment]
reverted, you can postponed this one

**Comment by madewild** [comment]
@roberto-musmeci reminder...
We can organise a meeting with GISCO if easier.
@AThollard do you remember the name of the person we met in the past?

**Comment by AThollard** [comment]
Yes I do. It is REUTER Hannes (ESTAT)

**Comment by raphdom** [comment]
No answer until today, I will postponed this issue

**Comment by madewild** [comment]
My bad, I forgot to contact him... will do.

**Comment by raphdom** [comment]
They don't have such tiles, I will close this issue and open others to change specific things that we have discussed on the meeting with REUTER Hannes (ESTAT)
