### ISSUE TITLE
Handle multiple thematic objectives

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#350]
Projects allow multiple TOs but:

- only one icon is shown on the project detail page
- only one TO/icon is shown in project results (first one in the list or at random)
- so when we filter one one TO, some results appear to be outside this TO

We should improve the handling of these.
Follow-up to #256 and #283

**Comment by madewild** [comment]
This would be good to implement for 1.3.
@D063520 @DiaZork is is already available in the backend?

**Comment by madewild** [comment]
Available in the backend but tricky to display with 2 images

Example: https://kohesio.test.ec.europa.eu/en/projects/Q68696

**Comment by madewild** [comment]
@raphdom to discuss together for next release

**Comment by raphdom** [comment]
Ask REGIO graphic team to create 2 new icons (multiple thematic objectives and react)(related #736)

**Comment by madewild** [comment]
What's the status with this icon? Should we postpone?

**Comment by raphdom** [comment]
I already have the icons, I will close when it is done...

**Comment by raphdom** [comment]
Should be good now
Can yout test, @madewild and @roberto-musmeci

**Comment by madewild** [comment]
Perfect
