### ISSUE TITLE
Rename repo to kohesio-frontend

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#388]
To be aligned with kohesio-backend
Caution: needs to be aligned with https://github.com/ec-doris/gitops-kohesio to avoid breaking the CI/CD pipeline!
(note: the URL https://github.com/ec-doris/kohesio.eu will still work, Github will handle the redirection)

**Comment by raphdom** [comment]
now kohesio-frontend

**Comment by madewild** [comment]
fyi I have created https://github.com/kohesio
at some point in the future we might consider moving away from the doris org...
