### ISSUE TITLE
Slowness issue with PulseSecure

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#419]
Probably linked to proxy rather than VPN.
To investigate further...

@AThollard @gachpas apparently it could also be linked to an outdated antivirus but I guess all updates have been applied?

**Comment by gachpas** [comment]
@madewild , yes, my security updates are OK.

**Comment by AThollard** [comment]
@madewild mine as well, I have updated everything following my call to the helpdesk last week

**Comment by madewild** [comment]
Yes I thought so.
This morning we experienced a delay of ~3 hours for the DNS propagation of kohesio.eu -> kohesio.ec.europa.eu whereas without the VPN/proxy it took less than one minute :-/
Apparently the proxy randomly assigns you to one server in Luxembourg, and if that server happens to be busy orfaulty or whatever then you will experience extreme solowness. There is not way to change that and other will have no trouble since the proxy links them to another server. To be confirmed.

**Comment by madewild** [comment]
@gachpas @AThollard just to check if the issue was eUI-related: do you still experience the slowness on https://kohesio.development.ec.europa.eu/ ?

**Comment by gachpas** [comment]
@madewild , yes I do :(

**Comment by madewild** [comment]
OK good to know. We'll narrow it down. :)

**Comment by madewild** [comment]
I am a bit at a loss with this issue... @Drino-San do you think you could help?

**Comment by madewild** [comment]
We recorded a JSON profile in Chrome with @gachpas and sent a ticket to DIGIT through MITS... Sandrino can push if we get no answer.

**Comment by madewild** [comment]
After DIGIT investigation, seems to be an issue of DNS delegation.
Basically the proxy is waiting while the domain name is going round the world to be resolved.
Should be fixed next week...

**Comment by gachpas** [comment]
@madewild Good news ;)

Well done!

**Comment by madewild** [comment]
@gachpas @AThollard can you check if the issue is gone for you?

**Comment by gachpas** [comment]
@madewild (cc: @AThollard ),
seems solved in dev for me ;)
Thanks

**Comment by madewild** [comment]
Wonderful! can you test the other environments as well?

**Comment by AThollard** [comment]
It's better but not ideal on my side :-(

**Comment by AThollard** [comment]
I keep testing but I think I will disconnect from pulse later for the Board meeting

**Comment by gachpas** [comment]
@madewild , acceptance NOK.

Prod is with the countdown.

**Comment by AThollard** [comment]
I am testing on acceptance

**Comment by AThollard** [comment]
So I keep the demo on acceptance later on or on test? or I just disconnect from Pulse?

**Comment by gachpas** [comment]
@AThollard , for me acceptance is still slow too. Max is checking if DIGIT has deployed the fix on all env.

**Comment by AThollard** [comment]
thanks @gachpas so I will do the demo on acceptance but disconnected from Pulse

**Comment by madewild** [comment]
I confirm the fix is deployed on DEV and TEST but not yet on ACC, checking with DIGIT.
For PROD we cannot really test now, need to wait until Wednesday when we remove the countdown...

**Comment by madewild** [comment]
No it should be working on ACC as well, @gachpas do you confirm? :)

**Comment by gachpas** [comment]
@madewild  (cc: @AThollard ), yes, it works now on acceptance too :):):)

**Comment by madewild** [comment]
Finally closing this!
