### ISSUE TITLE
Help tooltips missing

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#423]
In the filters, the help tooltips to explain how to use 1. keywords and 2. type of beneficiary (public/private) are missing

_Originally posted by @madewild in https://github.com/ec-doris/kohesio.eu/issues/405#issuecomment-1039522499_

**Comment by raphdom** [comment]
Maybe the angular material tooltip component:
https://material.angular.io/components/tooltip/overview

**Comment by raphdom** [comment]
@svili  You can do in the beneficiaries list

**Comment by svili** [comment]
Unfortunately Angular Material Tooltip doesn't support HTML content by design:
https://github.com/angular/components/issues/5440#issuecomment-313740211

**Comment by madewild** [comment]
Shit, we really need it for the keywords because operators are complex... can we develop something custom or import from elsewhere?

**Comment by raphdom** [comment]
we could put it no a modal for now?
...or another idea is have a button to collapse the header and have this bellow the label like they have in ECL, but it will take too much space:
<img width="284" alt="Screenshot 2022-02-16 at 16 50 59" src="https://user-images.githubusercontent.com/5124917/154302577-4d50b396-e1a3-476f-be42-3e3b898b9933.png">

**Comment by svili** [comment]
We can probably do it via plain CSS, I'll try.

**Comment by madewild** [comment]
When it's ready, you can add this (slightly adapted) text to the keywords tooltip:

```html
    <p>By default, semantic search automatically expands your keywords to similar words (searching for <b>ai</b> will also include results containg <b>artificial intelligence</b> as well as <b>machine learning</b> for instance). To disable keyword expansion and revert to classic (strict) search, use double quotes (<b>"ml"</b>).</p>
    <p>The operator AND can be used for conjunction: <b>green AND carbon</b> only retrieves documents containing both words in any order.</p>
    <p>To also include documents containing either word, use <b>green OR carbon</b>.</p>
    <p>To exclude one term from the results, you can you the - (NOT) operator : <b>green -carbon</b> (projects containing "green" but not "carbon").</p>
    <p>You can also search for an exact expression using double quotes: <b>"artificial intelligence"</b> only returns results with the words in that order.</p>
    <p>Additionally, you can use the star operator as a wildcard: <b>govern</b>* will match government, governing, governors, etc. (minimum 3 characters before the *).</p>
```

**Comment by svili** [comment]
I'm getting there, there was a bunch of problems with dependency conflicts with certain packages and that a bunch of libs are not compatible with angular 13 or something.
In the end I managed to do it with an angular wrapper of PopperJS.
The only thing that remains is to make it mobile friendly.
![image](https://user-images.githubusercontent.com/11196689/154920890-afdf047e-9173-45ce-9389-b2f502f5a2e3.png)

**Comment by madewild** [comment]
I notice I left a mistake in the text of the first paragraph, should be: use double quotes (**"ai"**)

**Comment by raphdom** [comment]
Good jog @svili. I've check and everything is fine and working, even on mobile is very good placed. Thank you
