### ISSUE TITLE
Hide outermost region ribbon

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#448]
The outermost regions ribbon stays there empty instead of disappearing completely when non-relevant country (e.g. Germany) selected:
![outer_stays](https://user-images.githubusercontent.com/942488/154140125-2a97333f-8562-4060-9ceb-ddab047ad498.png)

_Originally posted by @madewild in https://github.com/ec-doris/kohesio.eu/issues/400#issuecomment-1040737838_

**Comment by raphdom** [comment]
this is fixed. Can you check @madewild ?

**Comment by madewild** [comment]
Perfect.

**Comment by AThollard** [comment]
Hi @madewild @raphdom 
Sorry to reopen the issue but could you please hide the ribbon when we are on the map tab as well?
![image](https://user-images.githubusercontent.com/80402472/155361163-925e9a5c-b12b-4a3e-bfac-c7c16d942fa9.png)

**Comment by raphdom** [comment]
@AThollard fixed and hidden like we had in the previous version. I've created another issue(https://github.com/ec-doris/kohesio-frontend/issues/571) to improve on version 1.2 using the filters also
