### ISSUE TITLE
Proofreading

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#461]
Some texts (e.g. About page) are not written in perfect English... would be good to have a native English speaker proofread the whole website before the launch. @AThollard can you find someone in REGIO?

**Comment by AThollard** [comment]
Ok, first we need to revise the content then I will find someone @gachpas I think Simon in our unit would do that.

**Comment by gachpas** [comment]
@madewild , I will update the About page and will have it validated by Anne and proofread by Simon.

In the meantime, I am wondering on which ticket I can provide you updated information for the social network in the footer (cas confirmed by our Social media team)?
Here they are:
- Linkedin can be removed
- Insta and youtube to be added with the following links:
-[EU in my Region (@euinmyregion) • Instagram photos and videos](https://www.instagram.com/euinmyregion/)
https://www.youtube.com/c/EUinmyRegion
Pascal
CC: @AThollard

**Comment by madewild** [comment]
For the footer, please use #298 
For the about page, I reopened #222

**Comment by AThollard** [comment]
Hi @madewild, "[About](https://eceuropaeu.sharepoint.com/:w:/r/sites/GRP-REGIOKMteam/Shared%20Documents/Kohesio%20Com%20-%20presentations/About%20-%20FAQ/Kohesio%20about.docx?d=wbed9d140df524e339636860c808e6b89&csf=1&web=1&e=BbZfnx)" amended version ready in Teams

[Kohesio about.docx](https://github.com/ec-doris/kohesio-frontend/files/8115240/Kohesio.about.docx)

FYI: @gachpas @roberto-musmeci

**Comment by madewild** [comment]
So the proofreading is finished? If yes we can close this issue and follow up on the about page in #222

**Comment by AThollard** [comment]
yes
