### ISSUE TITLE
Image overlays

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#473]
create another component to the image overlay on project list, project detail and beneficiary detail pages.

_Originally posted by @raphdom in https://github.com/ec-doris/kohesio.eu/issues/415#issuecomment-1042295750_

**Comment by madewild** [comment]
Should be implemented in 3 places:

- [ ] https://kohesio.development.ec.europa.eu/projects
- [ ] https://kohesio.development.ec.europa.eu/projects/Q100952
- [ ] https://kohesio.development.ec.europa.eu/beneficiaries/Q2514974

Compare with https://prod.kohesio.eu/projects?tab=results etc.

**Comment by madewild** [comment]
Good for the functionality but maybe we could still improve the CSS for the credits? I preferred the former version:

![overlay_prod](https://user-images.githubusercontent.com/942488/155201080-0fe1056d-b9aa-4336-a7c9-bcf5974289f0.png)

**Comment by svili** [comment]
I agree that some changes should be made.
I truncated the title length and dropped the default ECL styling of the figcaption. But Im not sure I'd use the caption style of the old version cause it looks quite outdated and doesn't really fit the ECL look.
Right now it looks like this on my local.
Im open for suggestions of course, not really big on designing.
![image](https://user-images.githubusercontent.com/11196689/155299866-e4439df5-63dd-472a-905b-96fef4791994.png)

**Comment by madewild** [comment]
Good enough for me!

**Comment by raphdom** [comment]
on my view we should have a close button. You can check in the modal that we have for the project detail.

**Comment by madewild** [comment]
Thanks @svili 
can you add the red cross like on the map modal?
![modal_close](https://user-images.githubusercontent.com/942488/155305432-87e4afa0-0ac1-4196-aa54-344a03ea59ad.png)

then I think we can close

**Comment by svili** [comment]
Oh sorry, I didn't notice this, I added the ECL close icon, should I change it?
![image](https://user-images.githubusercontent.com/11196689/155381154-73600f5e-ff35-46ab-9a52-ab90a9d96911.png)

**Comment by raphdom** [comment]
I am fine with this. @madewild ?

**Comment by madewild** [comment]
For me too, don't worry.
