### ISSUE TITLE
Graph and More buttons

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#481]
Currently the buttons Graph and More are in a div of their own and take a lot of vertical space, we should consider moving them elsewhere.
Also, is there a way to add back the icons or we keep like that for simplicity?

**Comment by madewild** [comment]
With the space #469 removed it already looks much better
@roberto-musmeci do we leave like https://kohesio.development.ec.europa.eu/projects/Q100952 or needs extra improvements (icons etc.)?

**Comment by roberto-musmeci** [comment]
It looks already good! 
Maybe another option would be using the link with icon component (see (here)[https://ec.europa.eu/component-library/ec/components/navigation/link/code/]). so we reduce the white space and put less enfasis on these two functionalities which are in general less relevant for the public.

**Comment by madewild** [comment]
@raphdom what do you think?

**Comment by raphdom** [comment]
For me buttons that are on the top right of the page are to do edit the content or actions related to the content itself. Maybe we could move those buttons to a link inside a grey box on the left? Like you said too much attention and is not so relevant to the public...

**Comment by madewild** [comment]
At the same time the 3 buttons are aligned in the modal:
![open_graph_more](https://user-images.githubusercontent.com/942488/154951232-d1477d54-da15-4123-82df-afaaa45059c2.png)

I propose leaving like that for now and reviewing for next version.

**Comment by madewild** [comment]
For later, maybe we should move the social sharing buttons to the top instead. We just need to figure out where to place the "Open" in the modal...

**Comment by madewild** [comment]
fyi @AThollard

**Comment by madewild** [comment]
Let's review it for 1.3

**Comment by madewild** [comment]
@AThollard @roberto-musmeci any suggestion of change or we leave like that and close this issue?

**Comment by AThollard** [comment]
For me it's fine as it is. We have abandoned the 'Open' button?

**Comment by madewild** [comment]
No it's still there, but only in the modal (from the homepage):
![open](https://user-images.githubusercontent.com/942488/186443439-e0013eb9-0669-4318-a0b7-861ea0904d8f.png)

**Comment by AThollard** [comment]
It makes sense as we only need to 'open' from the smaller window from the homepage. So you can close the issue.
