### ISSUE TITLE
Don't go back to top of header after searching keyword

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#492]

**Comment by raphdom** [comment]
I don't understand this issue, seems the same as #496 ?

**Comment by madewild** [comment]
side effect of jumping to the top for about/privacy etc

**Comment by madewild** [comment]
For me it makes sense to go back to the top when you get new results...
Or @D063520 can you explain a bit more?

**Comment by D063520** [comment]
ehmmm ... I think it is still there this effect but either I got used to it or we made some changes and it is better now. For me we can close it. 

In general the effect is, when you search a keyword and you press enter, then the viewport is moved again up.
