### ISSUE TITLE
Make projects more accessible on map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#505]
It is mandatory to click until the finest NUTS level is reached in order to display "blue bullets" (projects) appears. 
For a newcomer it is not very obvious that such bullet are available, it kind of "kills the functionality".

**Comment by madewild** [comment]
@roberto-musmeci @gachpas any ideas to improve this?
add a text to tell people to select one subregion first?

**Comment by gachpas** [comment]
@madewild  (cc: @roberto-musmeci ), indeed adding a text when clicking like: "Click further to reach finest granularity and once at subregion level, discover clickable projects"

**Comment by raphdom** [comment]
I think it is already intuitive and on my view we already have many things that can distract on the map. 
If you have any other suggestion, but like @madewild said, we have the disclaimer, not easy to find a place to put this.

**Comment by madewild** [comment]
@AThollard @gachpas @roberto-musmeci we need a decision on this...

**Comment by madewild** [comment]
Try auto-disappearing pop-up "Select a subregion to see individual projects"

**Comment by raphdom** [comment]
It is on dev:
Can you check it? @madewild @gachpas @roberto-musmeci 
<img width="1177" alt="Screenshot 2022-09-07 at 15 23 12" src="https://user-images.githubusercontent.com/5124917/188889340-966b37fb-ad79-4853-9356-ac883dac19ed.png">

**Comment by madewild** [comment]
Looks good to me! :)

**Comment by roberto-musmeci** [comment]
Perfect for me too. We can close it ;)

**Comment by gachpas** [comment]
Good to me too :)
only remark, is the colour code also adapting for the Outermost regions? It looks like they stay with the standard colour...
Thanks and kr

**Comment by madewild** [comment]
This is more a discussion for #534
