### ISSUE TITLE
Improve readability of long labels in map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#507]
In blue bullet contextual tooltip, project labels could benefit from better readability (text column is narrow). 
When project label is very long, layout is negatively impacted.

**Comment by raphdom** [comment]
can you check please?

**Comment by madewild** [comment]
@roberto-musmeci @gachpas @AThollard what do you think about this solution with projects separated by horizontal lines ?
you can check on dev
![horizontal](https://user-images.githubusercontent.com/942488/169825371-2766c6cf-662d-4c98-9b1b-141fc9989f0a.png)

**Comment by gachpas** [comment]
@madewild , in my view, the original presentation is good enough but if I had to make a change, I would prefer bulleting the existing list vs horizontal lines.


but it is  jus mho :)

**Comment by madewild** [comment]
The difference is that full titles are readable now, that the main change.

**Comment by AThollard** [comment]
I prefer the new version, more readable. And the separators are fine as well. I don't think Roberto will have a strong opinion on that. So for me you can go ahead (sorry for the bullets @gachpas ;-))

**Comment by madewild** [comment]
I don't like lines/bullets either, so here I suggest a solution without border-bottom:
![noline](https://user-images.githubusercontent.com/942488/169829245-e6349df1-1759-45bc-83f6-ae7865943316.png)

**Comment by raphdom** [comment]
for me I agree with Anne, the version with the small line is the best, without a line it is very easy to get confused with a lot of labels...

**Comment by madewild** [comment]
OK as you wish, for me we can go ahead with this...
