### ISSUE TITLE
Mobile - call for action button do not work

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio-frontend#522]
On the carousel, call for action buttons are not active: Explore the map/Browse the project / Download the data 
Samsung /Android

**Comment by raphdom** [comment]
@omar0z  Seems that we have a problem with the ECL carousel component, even in the playground on mobile the actions doesn't work. I think it is related to the swipe action that overlap the buttons...

**Comment by madewild** [comment]
ah damn... I hope we don't have to change the carousel component again :(

**Comment by madewild** [comment]
Thank you @omar0z !
@AThollard can you test on dev on mobile?

**Comment by AThollard** [comment]
Hello,
Thanks it works better. But 'Browse the project' button leads to an 'error 404' page @omar0z  @madewild

**Comment by AThollard** [comment]
Ok already fixed? works fine now

**Comment by madewild** [comment]
we did not touch anything ;)

**Comment by AThollard** [comment]
Strange...I really had an error 404 for 2 minutes...anyway, it works fine now.
@roberto-musmeci can you please double check?
And then we can close the issue :-) Thank you for having fixed this, it was a very important one!

**Comment by roberto-musmeci** [comment]
It works on my side as well :)
