### ISSUE TITLE
Better visual indication of project numbers on the map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#534]
If you want to search on a TO or keyword and see all related projects in Europe, when passing to the map view, you have to hover to see if there are projects or not…there is no direct visual sign of where projects are or which countries have such projects.

https://kohesio.development.ec.europa.eu/projects?theme=Research-%26-Innovation&policyObjective=Smarter-Europe&sort=Total-Budget-(descending)&tab=map

we might investigate different shades of orange for instance

reported by @gachpas

**Comment by madewild** [comment]
Updated URL: https://kohesio.test.ec.europa.eu/en/projects?theme=Research-and-innovation&policyObjective=Smarter-Europe&sort=Total-Budget-(descending)&tab=map

@raphdom could we do a test with darker shades of orange or too difficult?

**Comment by raphdom** [comment]
Yes we can try, but we need kind of legend to the map, something like this:
<img width="662" alt="Screenshot 2022-08-25 at 10 27 02" src="https://user-images.githubusercontent.com/5124917/186615106-59f1e695-d338-418d-ba20-ad7d3e03c192.png">

**Comment by madewild** [comment]
@AThollard @gachpas what do you think?

**Comment by AThollard** [comment]
With a legend on the legend: "Number of projects"

**Comment by AThollard** [comment]
For me it's fine, to be tested.

**Comment by raphdom** [comment]
The first version is on dev, can you check it, please @madewild @gachpas @roberto-musmeci

**Comment by madewild** [comment]
@gachpas do we want this feature only on https://kohesio.development.ec.europa.eu/en/projects?tab=map or also on the homepage?

**Comment by gachpas** [comment]
Hello @raphdom and @madewild ,

I would say on homepage too, but would let the final decision to Diego and @roberto-musmeci.

This being said, I have serious performance issue for loading the map. Do you have the same?
This may also influence the decision on implementing on the homepage...
Br,
Pascal

**Comment by raphdom** [comment]
The performance is not related to the new feature, we are facing some problems on dev, maybe I could merge it on test...

**Comment by gachpas** [comment]
@raphdom , ok then.
for merging with test, I let Max decide with you what is best :)

**Comment by gachpas** [comment]
I will speak to Diego and Roberto and will come back to you

**Comment by madewild** [comment]
Yes go ahead :)

**Comment by raphdom** [comment]
deployed on test @madewild @gachpas

**Comment by gachpas** [comment]
it is better in terms of performance, though sometimes not direct when going deeper in a country but acceptable.
When speaking with Diego and Roberto, I will also challenge the range proposed in the legend, as, at the moment, it is a bit too wide...we will see...I suppose that this something we can adapt, right?

**Comment by raphdom** [comment]
Indeed, the colors and the range can be adapt.

**Comment by roberto-musmeci** [comment]
we discussed with @raphdom and @madewild to keep the heat map only in the map tab of the project detail page.

**Comment by raphdom** [comment]
Ok, now should be good, the heat map is only on the map tab(projects page) and with dynamic range now, can you check if all is good? @madewild @roberto-musmeci @gachpas 
Still have some doubts about the outermost regions, which color should appear (tricky)

**Comment by roberto-musmeci** [comment]
This is very good @raphdom. Thanks.
If you mange also with the outermost regions, I think that for this version is perfect

**Comment by raphdom** [comment]
For now the outermost regions will be gray in the heatMap, I will create a new issue to adapt the colors of the outermost regions when we are in the country level, that we have this information. Can we close it? @madewild @roberto-musmeci @gachpas ?
