### ISSUE TITLE
Enhancement - footer "twitter" mention

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio-frontend#539]
Comments from Regio Social Media team
Is it possible to add the[ #Kohesio](https://twitter.com/search?q=%23kohesio&src=typed_query&f=live) under "Twitter" button in the footer?
If not possible link the Twitter button itself to https://twitter.com/search?q=%23kohesio&src=typed_query&f=live

**Comment by madewild** [comment]
So Facebook, Instagram and Youtube will all go to "EU in my region" but Twitter will behave differently and go to #Kohesio ?

**Comment by madewild** [comment]
@AThollard you can test it on dev:
![koh_hashtag](https://user-images.githubusercontent.com/942488/154950147-3c7e9dd9-4a56-4ee3-84e6-c1ec8b74468c.png)

**Comment by AThollard** [comment]
Yes, because there is a specific hashtag for Kohesio now. I send the test Corinne, my Social Media colleague

**Comment by madewild** [comment]
@AThollard can you check now?

![hash2](https://user-images.githubusercontent.com/942488/154974140-360de304-2554-49cc-85da-3b159ffd49f2.png)

**Comment by AThollard** [comment]
You can get rid off the parenthesis and it will be perfect

**Comment by madewild** [comment]
For me it's strange to have just "Twitter #Kohesio" with two links...
What about "Twitter - #Kohesio" then if you don't like the parentheses?
Or again, just Twitter with the Kohesio link behind.

**Comment by madewild** [comment]
![twitter_final](https://user-images.githubusercontent.com/942488/155107938-2d36f861-0f11-49ce-97f9-9843ff53633d.png)

**Comment by AThollard** [comment]
You can close it :-)
