### ISSUE TITLE
Interaction between fund and programme filters

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-frontend#541]
In the https://kohesio.test.ec.europa.eu/projects?tab=results, the program filter does not work properly. 
It you select ESF as fund, you can still find ERDF programs in the program filters. See screenshot, "RF" (position 10 in the CCI) indicates it is a ERDF program. 

I tried with Germany and Austria. It seems an overarching issue. 

![image](https://user-images.githubusercontent.com/86654885/154237130-408b4adc-9510-4678-b765-2f57bdf6eb55.png)

**Comment by madewild** [comment]
In the future we will also make policy/theme inreraction work like this, see #551

**Comment by svili** [comment]
@DiaZork can you check if this works? For me it seems the fund parameter doesnt do anything right now. It returns all programmes of the country no matter what.
![image](https://user-images.githubusercontent.com/11196689/155183089-7d318bf8-305b-450d-aa8a-ec34c991a892.png)

**Comment by madewild** [comment]
Indeed @DiaZork there is a bug, Q2504369 should return the ERDF and Q2504370 the ESF...

https://query.linkedopendata.eu/#select%20%2a%20where%20%7B%0A%20%20%3Fprogramme%20wdt%3AP35%20wd%3AQ2463047%20.%0A%20%20%3Fprogramme%20wdt%3AP32%20wd%3AQ22%20.%0A%20%20%3Fprogramme%20rdfs%3Alabel%20%3FprogLabel%20.%0A%20%20%3Fprogramme%20wdt%3AP1584%20%3Ffund%20.%0A%20%20%3Ffund%20rdfs%3Alabel%20%3FfundLabel%20.%20FILTER%28lang%28%3FfundLabel%29%3D%22en%22%29%0A%7D

**Comment by DiaZork** [comment]
That's should be fix now

**Comment by madewild** [comment]
Working in dev now!
@roberto-musmeci I let you cross-check...

**Comment by roberto-musmeci** [comment]
Excellent guys, very good enhancement together with https://github.com/ec-doris/kohesio-frontend/issues/214)(https://github.com/ec-doris/kohesio-frontend/issues/214)n. Thanks and congrats ❤️
