### ISSUE TITLE
Add Cookie Consent Kit

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#546]
Note that the corporate service Cookie Consent Kit must be implemented on all pages of the website.
https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?spaceKey=webtools&title=Cookie+Consent+Kit

**Comment by raphdom** [comment]
implemented on dev

**Comment by madewild** [comment]
It contains a link to https://kohesio.ec.europa.eu/cookie-policy_en but this gives an nginx error

**Comment by madewild** [comment]
We can change to https://ec.europa.eu/info/cookies_en as we don't have a custom policy

**Comment by raphdom** [comment]
Changed to /cookie. Maybe we need to put something on that page?

**Comment by madewild** [comment]
No, we don't have any cookies
We just implement it because mandatory
Please put the EC default one https://ec.europa.eu/info/cookies_en
