### ISSUE TITLE
Pre-launch checks

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#547]
- [x] You are kindly requested to send mock-ups and the URL of the draft website to allow DG COMM the possibility to review the compliance with the Europa Web Guide prior to launch.
- [x] You are kindly requested to inform DG COMM of the exact date when the website goes live
- [ ] You are kindly requested to send a website accessibility evaluation report to DG COMM before the launch of the website.

**Comment by AThollard** [comment]
OK, taking care of that. So I will communicate acceptance still this week and I will ask @gachpas to follow-up on this.

**Comment by madewild** [comment]
@raphdom will merge into ACC tomorrow

**Comment by madewild** [comment]
Email sent
