### ISSUE TITLE
Outermost region ribbon width 

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-frontend#552]
In  [prod](https://prod.kohesio.eu/) the width of the outermost region ribbon matches the one of the project near me button. This is not the case in [test](https://kohesio.test.ec.europa.eu/)

If we have time, it would be great to restore that. No big issue otherwise.

**Comment by raphdom** [comment]
fixed on dev

**Comment by madewild** [comment]
Sorry to be picky but:
- the margin to the right is not the same for PNM button and OR ribbon (button is closer to map border)
- the OM ribbon has a border so it's actually 2px wider than the button ;)

**Comment by raphdom** [comment]
done
