### ISSUE TITLE
Enhancement - Map breadcrumb (detail - not urgent)

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio-frontend#556]
Why do we have an arrow to reduce the map when positioned on 'Europe'
![image](https://user-images.githubusercontent.com/80402472/155119983-ef4d1f86-9e98-47eb-af27-3bf168180b0c.png)

**Comment by madewild** [comment]
Because it cas take some space on mobile...

**Comment by AThollard** [comment]
Ok, maybe good to hide it on the desktop version, but really a minor detail

**Comment by madewild** [comment]
This arrow does not care if we have one or two or three levels open, it just closes the breadcrumb.
Can we keep this behavour?

**Comment by AThollard** [comment]
So let the arrow alive ! Fine with me and you can close this issue
