### ISSUE TITLE
Map not rendering due to 403 error

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#560]
I get this currently ....
<img width="1680" alt="Screenshot 2022-02-22 at 19 25 37" src="https://user-images.githubusercontent.com/10883585/155195451-2942831e-a93b-4402-bda7-add7c109ccb5.png">

**Comment by madewild** [comment]
Damn... not much we can do since it comes from the Eurostat webtools...
@raphdom have you seen this before?

**Comment by raphdom** [comment]
yes, on codeweek, the problem is more on their side, hope that tomorrow will be more stable. I cannot reproduce it on my computer, maybe because it was cached...

**Comment by madewild** [comment]
Me neither, I guess it's already gone... Will close tomorrow if all is fine.
