### ISSUE TITLE
Regresion on dev (urgent)

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#563]
The version that we have one dev with the changes of today break some other things that we fixed before:

-Scroll up for all pages
-In page navigation for privacy page

Can you help me to check which change affect this?

Use this link to see the changes
https://github.com/ec-doris/kohesio-frontend/compare/test...dev

**Comment by madewild** [comment]
Probably because I also added inpage nav to FAQ...
https://github.com/ec-doris/kohesio-frontend/commit/4479de84f671763ab1294e5a67102ecae5d52ee7
should I use different variable names? I let you check

**Comment by madewild** [comment]
was working on my local :(

**Comment by madewild** [comment]
Actually no it's you @raphdom !

https://github.com/ec-doris/kohesio-frontend/commit/8c6b3c04aa35a57b3b6dc7fa1f8ebe214d3dc720

removing

```css
html, body {
  overflow-x: hidden;
}
```

fixed the problem for me :)

**Comment by madewild** [comment]
Solved but you need another solution for the horizontal scrollbar...

**Comment by raphdom** [comment]
indeed, thank you to spotted. I've fixed in another way...
