### ISSUE TITLE
Social links don't work in modal

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#564]
The social links are constructed based on the QID. For instance for Facebook:

```javascript
'https://www.facebook.com/sharer/sharer.php?u=' + currentUrl
```

works fine on https://kohesio.development.ec.europa.eu/projects/Q151756, URL gets constructed as "https://www.facebook.com/sharer/sharer.php?u=https://kohesio.development.ec.europa.eu/projects/Q151756"

but in the modal we don't have the correct "currentUrl" info (we are still on the homepage) so the Facebook URL is "https://www.facebook.com/sharer/sharer.php?u=https://kohesio.development.ec.europa.eu/" !

normally we know the QID so can we construct the URL differently?

**Comment by raphdom** [comment]
fixed
