### ISSUE TITLE
on map not clear if loading or no result

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#577]
<img width="1680" alt="Screenshot 2022-02-24 at 09 25 24" src="https://user-images.githubusercontent.com/10883585/155486521-ffe9cae8-2db2-43dd-ad35-08817a792a5c.png">

**Comment by madewild** [comment]
For me it's the same as #576

**Comment by D063520** [comment]
true ... would have put it in this version though .....

**Comment by madewild** [comment]
@raphdom what do you think?

**Comment by raphdom** [comment]
yes, seems to me the improvement of the map on the search
