### ISSUE TITLE
front-end wrongly calling map API

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#578]
the map API is called with a total budget parameter. this is not good for performance and is not necessary for the map. Please take care to never pass any sorting parameter. We probably should even remove them from the REST API

<img width="1680" alt="Screenshot 2022-02-24 at 09 32 58" src="https://user-images.githubusercontent.com/10883585/155487972-44e16970-97ac-47d5-a3e1-56cd9ed6e326.png">

Related to [#151](https://github.com/ec-doris/kohesio-backend/issues/151)

**Comment by raphdom** [comment]
now, there is no sort in the parameters, on dev

**Comment by madewild** [comment]
What is the issue exactly?
https://kohesio.development.ec.europa.eu/projects?country=Finland&region=Finland-Proper&sort=Total-Budget-(descending)&tab=map

**Comment by madewild** [comment]
ah "no sort" passed as parameter I guess, ok

**Comment by raphdom** [comment]
Yes, I remove the sort, there is "no sort" in the parameters anymore (for the map request)

**Comment by madewild** [comment]
OK closing
