### ISSUE TITLE
Prevent going to page over pagination total

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#580]
1) go here https://kohesio.development.ec.europa.eu/beneficiaries?page=3&name=water&country=Italy
2) click on search
3) refresh the page

**Comment by madewild** [comment]
because page 1 is not explicit in the URL (on purpose)

question is: how did you arrive on https://kohesio.development.ec.europa.eu/beneficiaries?page=3&name=water&country=Italy in the first place since it does not exist ??

**Comment by D063520** [comment]
the UI generated it .... but you see it start with an empty search, put the same search parameters and check the URL

**Comment by madewild** [comment]
I don't understand... can you explain step by step how you arrive on this URL?

**Comment by D063520** [comment]
strange I cannot reproduce it anymore .... I will close it

**Comment by madewild** [comment]
Maybe we could redirect to 404 when page number is over total...
@raphdom worth keeping for 1.2 ?

**Comment by raphdom** [comment]
already closed no?

**Comment by madewild** [comment]
Yes but https://kohesio.development.ec.europa.eu/beneficiaries?page=30&name=water&country=Italy looks weird, even if you can only arrive that by tweaking the URL (which Dennis obviously did not do so there might be somthing in the UI generating this king of fake url).

**Comment by raphdom** [comment]
okay, if it is not urgent and not block situation I would say put it to 1.2

**Comment by raphdom** [comment]
fixed, you can test it on dev and test environments...

**Comment by raphdom** [comment]
collateral effect with another issue, now the behaviour is, if the page is out of the range it will go to page 1 and remove page parameter from queryParams... the same for projects page, can you test it again @madewild

**Comment by madewild** [comment]
Great!
