### ISSUE TITLE
Sort beneficiaries by total budget

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#584]
Current is by EU contribution
Align with projects and use total budget instead?

**Comment by madewild** [comment]
@roberto-musmeci we need a decision about this...

**Comment by madewild** [comment]
check the cache

**Comment by raphdom** [comment]
Can we change it first on the backend side? so no sort means sort by Total Budget(descending), otherwise we the user enter in the page the url will be changed to add the sort, this is weird... It is easy @D063520 @DiaZork ?

**Comment by DiaZork** [comment]
It's not complicated

**Comment by raphdom** [comment]
@madewild we should do it, or postponed? The query maybe should be cached, non?

**Comment by madewild** [comment]
Not urgent, we can postpone

**Comment by DiaZork** [comment]
For the moment, by default it order EU contribution if we don't specify anything.
So do you want that It order by total budget by default or i remove the default order by and we specify in the call from the frontend how to order it ?

**Comment by madewild** [comment]
The idea would be to have total budget by default without specifying the parameter. But we need to cache this!

**Comment by DiaZork** [comment]
Okay, I made the change in the backend, and it should be cached too.

**Comment by raphdom** [comment]
Total budget(descending) is the new sort for beneficiaries list. Can you test it @madewild and close?

**Comment by madewild** [comment]
I see it but the search on beneficiaries is broken now @DiaZork !
https://kohesio.development.ec.europa.eu/en/beneficiaries?name=roads returns nothing while https://kohesio.ec.europa.eu/en/beneficiaries?name=roads has 10 results

**Comment by raphdom** [comment]
now it is working again, can we close it @madewild ?
