### ISSUE TITLE
Add new Kohesio FMB

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#585]
Replace functional mailbox

**Comment by madewild** [comment]
REGIO-KOHESIO@ec.europa.eu

**Comment by madewild** [comment]
Changed on:

- https://kohesio.development.ec.europa.eu/ (footer)
- https://kohesio.development.ec.europa.eu/about (Contact)
- https://kohesio.development.ec.europa.eu/privacy#section-9
- https://kohesio.development.ec.europa.eu/faq#section-6

@gachpas can you cross-check everything and confirm I did not forget any other page?
It will be merged into TEST tomorrow and into ACC on Monday.

**Comment by gachpas** [comment]
@madewild , it looks OK to me ;)
Thx
