### ISSUE TITLE
Hide Commission logo in footer

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#590]
According to DG COMM, the logo of the Commission can’t be used in the footer.

**Comment by madewild** [comment]
This seems coherent with https://ec.europa.eu/component-library/ec/harmonised-templates/footer/group1/

Not sure how the logo got there in the first place... bug in ECL template?

**Comment by raphdom** [comment]
done, in the playground for the group1 we have the logo in the footer, it was there that we copy the styles and html. Anyway, doesn't hurt to remove it
https://ec.europa.eu/component-library/playground/ec/?path=/story/components-footers-harmonised--group-1

**Comment by madewild** [comment]
Thanks for the link, @AThollard please share with DG COMM when replying to comments.
