### ISSUE TITLE
Unselecting Intervention field

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#595]
when an intervention field is selected (for filtering the Projects page), you cannot go back unselect and re-select another one

**Comment by madewild** [comment]
You can, but currently you need to select the text and to delete it with the keyboard key (delete or backspace).
Let's see if we can improve this in the next version...

**Comment by madewild** [comment]
Yes much better for me, @gachpas can we close?

**Comment by gachpas** [comment]
Much better indeed :) Thx for that.
This ticket can be closed.
Checking this, I have seen something else that puzzles me a bit: if you are on a project fiche and click on the link under the Intervention field, you arrive on a page that - i assume - list all the projects for that intervention field.
What is a bit weird to me is that when looking into the advanced filter/Intervention field, this concerned intervention field is not selected....do you want me to log a ticket apart for this?

**Comment by madewild** [comment]
Mmmh good point, maybe @raphdom you can tackle this as part of this issue?

**Comment by raphdom** [comment]
Dennis had already logged this ticket, and I close it :) #701 , but in fact we are waiting the implementation of the ticket #536 to finish this part of the implementation.

**Comment by madewild** [comment]
Ah OK then :)
