### ISSUE TITLE
buggy link to exports

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#598]
<img width="1680" alt="Screenshot 2022-03-13 at 19 30 17" src="https://user-images.githubusercontent.com/10883585/158073933-bbbb33d2-43be-45a5-9d3e-0ae2ec47bc89.png">
For me the exports link ("this link") goes to a 404 ....

**Comment by madewild** [comment]
Good catch! It's a routerlink instead of href... fixed in dev but we cannot test, will merge into test and then we can move on to the other envs...

**Comment by madewild** [comment]
Fixed
