### ISSUE TITLE
Add disclaimer to map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#611]
See https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=81471704

Adding a general disclaimer

In addition to paying due attention to the specific examples described below, it might be a good idea that you put the following footnote on any map that shows national borders outside the EU. This is standard UN practice and should protect us to some degree from angry reactions from whatever country.

"The boundaries and names shown and the designations used on this map do not imply official endorsement or acceptance by the European Union." The translation by DGT on the [short version is available](https://webgate.ec.europa.eu/fpfis/wikis/download/attachments/81471704/TranslationsShortDisclaimer.docx?version=1&modificationDate=1646663432197&api=v2) as well.

In addition you could add a longer version with the same goal to the disclaimer section of your Europa website:

"The designations employed and the presentation of material on the map do not imply the expression of any opinion whatsoever on the part of the European Union concerning the legal status of any country, territory or area or of its authorities, or concerning the delimitation of its frontiers or boundaries." The translation by DGT are provided by DG COMM in [WEBTOOLS](https://europa.eu/webtools) in [maps-labels-disclaimer-only.json](https://webgate.ec.europa.eu/fpfis/wikis/download/attachments/81471704/maps-labels-disclaimer-only.json?version=1&modificationDate=1579893575061&api=v2)

**Comment by raphdom** [comment]
applied, we can keep it to the next to apply the i18n, the translated file is inside the documentation from webtools.
