### ISSUE TITLE
Track more actions in analytics

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#620]
For instance on the map...

**Comment by madewild** [comment]
@roberto-musmeci feel free to add more details

**Comment by roberto-musmeci** [comment]
Thanks @madewild 

I think essentially we need track which exact project is opened in modal from the map in the homepage and ideally how long users stay on that. 

This could help understanding the average "quality" of the content users are looking at. The time log could help determining the quality of the project description and from there promote or demote the visibility of the project. 

Let me know what you think :)
