### ISSUE TITLE
Idea: Add option to report data errors more easily 

### ISSUE THREAD

**Issue by hejjoe** [ec-doris/kohesio-frontend#623]
A button like "Report Error/Duplicate" could be a mailto link that includes the website URL near the displayed data - not in the footer. This could encourage more people to participate in improving data quality.

E.g.
```
<a class="email" title="Report an error or duplicate" href="#" onclick="javascript:window.location='mailto:?subject=Reporting error or duplicate&body=Please describe the error or the duplicate with the URLs: ' + window.location;">Email</a>
```

**Comment by madewild** [comment]
Hello @hejjoe, thank you for this suggestion! Indeed we had such a button at a stage (the email social media sharing button had this behaviour) but that was changed at some point... @AThollard what do you think?

**Comment by AThollard** [comment]
Hi @madewild I think it would be good to have an additional button 'report an issue' for that from project details and also beneficiary. (icon: https://www.flaticon.com/free-icons/problem-report)
Maybe just above the 'share' icones? I let you @madewild and @raphdom decide where it fits best.

**Comment by madewild** [comment]
@raphdom let's prepare this for the next release...

**Comment by madewild** [comment]
try at the bottom, right of "share on"
with bug icon?
separate with some spacing

**Comment by raphdom** [comment]
What do you think about this:
<img width="363" alt="Screenshot 2022-06-17 at 15 16 17" src="https://user-images.githubusercontent.com/5124917/174305738-9e873c35-0910-479e-b11d-f6bb0126bd03.png">

**Comment by gachpas** [comment]
@madewild , is the icon not copyright protected?

**Comment by madewild** [comment]
@raphdom I guess you chose something under creative commons?

**Comment by raphdom** [comment]
I am using the fontawesome:
https://fontawesome.com/icons/bug?s=solid

**Comment by AThollard** [comment]
Ok tested with one colleague (not the best scenario as he's British, but he was the only available). So for him the icon is fine specially with the text. And he told me that red would be better than green! For him the alternate icons in small format are not clear so forget my previous suggestion.

**Comment by Bisiaam** [comment]
I agree for the color. In my test, someone thought it was a green/ecological button (without the text)

**Comment by raphdom** [comment]
I've change the color, can you check please?

**Comment by AThollard** [comment]
Good for me as well!
