### ISSUE TITLE
Add keywords to html head

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#630]
To optimize SEO
https://www.w3schools.com/tags/tag_meta.asp
Fot instance `<meta name="keywords" content="Kohesio, ERDF, ESF, CF, projects, EU">`

**Comment by madewild** [comment]
@D063520 @AThollard @roberto-musmeci other ideas?

**Comment by roberto-musmeci** [comment]
"Cohesion" for sure . Can we also have acronymns of funds in other language ? 
How many keywards you suggest to have ?

**Comment by roberto-musmeci** [comment]
https://www.rankwatch.com/free-tools/meta-tag-analyzer

**Comment by D063520** [comment]
> checking this https://ec.europa.eu/regional_policy/en/funding/erdf/ @ https://www.rankwatch.com/free-tools/meta-tag-analyzer
> 
> we get these region, development, programmes, regional policy, structural funds, cohesion, europe, regio, regional, fund, erdf, funding, policy, projects, financing, investment, esi, esif, european commission, european union, eu, urban, interreg, territorial, cooperation
> 
> Read more: https://www.rankwatch.com/free-tools/meta-tag-analyzer#ixzz7RqMnk6TR

that is a good catch! probably something similar ....

**Comment by AThollard** [comment]
I think we should have: region, regional policy, cohesion policy, cohesion, projects, financing, EU, European union, funding, financing, investment, development, territorial, cooperation, urban, ERDF, ESF, CF, JTF, transition (structural funds, esi and esif not that sure because it's not used anymore in the current programming period)
And it's already a lot no?

**Comment by madewild** [comment]
The links I put above suggest 2 to 5 keywords perpage so... yes! :P

**Comment by AThollard** [comment]
And I forgot European Commission (but with European Union maybe we are covered).

**Comment by raphdom** [comment]
added
