### ISSUE TITLE
Add pagination below beneficiaries list

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#632]
On https://kohesio.ec.europa.eu/projects we have the pagination both at the top and bottom, which is nice.
But on https://kohesio.ec.europa.eu/beneficiaries it's only at the top, it would be good to add at bottom to align.
If we want to keep only one, it would be better at bottom (like Google), more logical when you reach the end of the list... but again we can keep both.

**Comment by raphdom** [comment]
fixed, you can test it on dev and test environments...

**Comment by madewild** [comment]
It's fine. Just one related thing, maybe you canb fix it at the same time (unless you prefer I open another issue): when clicking "next page" on the beneficiaries, the dropdown "EU contribution (descencing)" moves slightly to the left or to the right which is annoying. Some simple CSS should fix it inside the div as absolute instead of relative to the pagination. This does not happen on the Projects page...

**Comment by raphdom** [comment]
thanks to report... it is fixed now, can you re-check?

**Comment by madewild** [comment]
The issue is fixed but now the text is cut ;)
![contrib_cut](https://user-images.githubusercontent.com/942488/169031889-1b1e7c78-4987-4f8e-9cd9-33e7ee77d4f5.png)

Can you put a slightly larger width?

**Comment by raphdom** [comment]
now should be fine

**Comment by madewild** [comment]
Sorry @raphdom but when going to page 2 now the pagination info spreads over 2 lines :(
![pagi_2lines](https://user-images.githubusercontent.com/942488/169035743-1db3fd0d-336b-44a7-b422-458b891b5d32.png)

**Comment by raphdom** [comment]
ok, hope now everything is good... :)

**Comment by madewild** [comment]
Looks good now :)
