### ISSUE TITLE
CSVs in the data section - not UTF8 encoded

### ISSUE THREAD

**Issue by bogdan-necula** [ec-doris/kohesio-frontend#638]
Hi, the CSVs are not UTF-8 encoded. Maybe you could export the data with UTF-8 encoding

**Comment by madewild** [comment]
Thank you for reporting, we noticed this also and it has just been fixed in dev. It will be deployed to prod with the next release in June. In the meantime you can use the files here: https://kohesio.test.ec.europa.eu/data/
