### ISSUE TITLE
Add policy objective to project API

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#650]
Currently on https://kohesio.test.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q100952 we have:

"objectiveIds":["TO09"]
"objectiveLabels":["Social Inclusion"]

"objective" is not very clear since it can refer both to thematic objective (TO, theme) or policy objective (PO, policy)
it would be good for later to:

- change these to themeIds and themeLabels
- add policyId and policyLabel

But don't do it know since it will break the UI!

**Comment by D063520** [comment]
https://kohesio.development.ec.europa.eu/en/projects/Q100952 exmaple of broken UI due to this

**Comment by raphdom** [comment]
ok, now is good

**Comment by raphdom** [comment]
Can you check this @madewild ?

**Comment by madewild** [comment]
Looks good on https://kohesio.development.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q100952 !
