### ISSUE TITLE
Query TO by PO and PO by TO

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#651]
https://kohesio.development.ec.europa.eu/api/facet/eu/thematic_objectives should have an extra param ?policy
https://kohesio.development.ec.europa.eu/api/facet/eu/policy_objective should be renamed to polycy_objective**s** and have an extra param ?theme

First wait for https://github.com/ec-doris/kohesio-data/issues/213
For after launch!

**Comment by D063520** [comment]
Breaks probably https://kohesio.development.ec.europa.eu/en/projects

**Comment by raphdom** [comment]
okay, now is good

**Comment by raphdom** [comment]
Can you check this @madewild ?

**Comment by madewild** [comment]
Almost good but Technical assistance (T012 - https://linkedopendata.eu/wiki/Item:Q2577338) is missing in the list of themes when no policy is selected (it is not linked to a policy, special case).
@DiaZork can you add it on https://kohesio.development.ec.europa.eu/api/facet/eu/thematic_objectives ?

**Comment by madewild** [comment]
policy should be optional in the sparql query

**Comment by DiaZork** [comment]
It's fix in the backend

**Comment by madewild** [comment]
yes now I see TA on https://kohesio.development.ec.europa.eu/en/projects
great, closing

**Comment by D063520** [comment]
![Uploading Screenshot 2022-06-17 at 12.12.47.png…]()

**Comment by D063520** [comment]
@raphdom

**Comment by raphdom** [comment]
We have the same error in PROD, the Technical Assistance was related to Policy Objective(Q2577337) that doesn't exist. Don't know why. Another thing that I didn't understand well is now the API has the relation between theme and policy objective, still have this hardcoded in the frontend. I will try to implement it, but need to test all the cases on the filters (query params, map)...

**Comment by D063520** [comment]
It was hardcoded in the front-end but we want to get rid of that an have it in the data. This was the orginal motivation

**Comment by madewild** [comment]
Yes, this was the goal of this issue: #551 

Before we had a policy objective "Technical Assistance" linked to the theme of the same name, but this was a mistake so I deleted it. Technical assistance is a thematic objective (theme) with code TO12 but not linked to any policy. We should be able to use it normally as a filter in themes to see related projects, to be fixed.

**Comment by raphdom** [comment]
okay, now is not hardcoded anymore, the relationship is using the theme and policy parameters to get the themes and policies objectives correspondents in the API. on dev
