### ISSUE TITLE
Problem with intereg projects in multiple countries

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#656]
<img width="1728" alt="Screenshot 2022-06-17 at 11 07 05" src="https://user-images.githubusercontent.com/10883585/174266569-fa3c9a4b-af75-4598-8985-bd607bf039ff.png">
see multiple countries in API call

**Comment by raphdom** [comment]
Now, I've change to european flag, when we have more than one country code, on dev, can you check, please?
