### ISSUE TITLE
No icons for social media on safari browser only

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#659]
<img width="1121" alt="Screenshot 2022-06-20 at 13 18 57" src="https://user-images.githubusercontent.com/10883585/174590646-9f1ff31f-bf27-4ef6-9106-5b2d5958de9a.png">
https://kohesio.test.ec.europa.eu/en/projects/Q4301486

**Comment by raphdom** [comment]
now should be fine on dev
