### ISSUE TITLE
arrows missing in selection

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#660]
<img width="363" alt="Screenshot 2022-06-20 at 13 24 19" src="https://user-images.githubusercontent.com/10883585/174591617-c673584d-7215-4739-8fd1-60562a53ae51.png">

**Comment by madewild** [comment]
This is also on Safari? Fine on Chrome:
![chrome_arrows](https://user-images.githubusercontent.com/942488/174592046-1ba254f7-3ec7-4af0-91f8-37f19fa75aac.png)

**Comment by raphdom** [comment]
indeed, the same problema as before

**Comment by raphdom** [comment]
fine on dev, can you test it?
