### ISSUE TITLE
Shorten "missing intervention field" text

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#661]
On https://kohesio.development.ec.europa.eu/en/projects?country=Cyprus&sort=Total-Budget-(descending) for instance
The text "Intervention field not declared by the Managing Authority" is very long and does not show well with the new ECL look & feel.
![notdeclared](https://user-images.githubusercontent.com/942488/174593693-b37443c4-7b9f-4c2a-8928-bc055da4c387.png)

Could we shorten this text to just "Intervention field not declared" for instance?

**Comment by raphdom** [comment]
Done, you can check and close it @madewild or @roberto-musmeci
