### ISSUE TITLE
Improve CSV exports

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#664]
Whats not done:
- Still don't know why the cronjob didn't fire for days, but now its working.
- There is an issue with managing authorities only for Italy because of the special nature of the exporting there. But I think this is a separate issue.
- The data is still reachable on https://kohesio.test.ec.europa.eu/data/ , I dont think we want to change to data.kohesio.xyz in the middle of a release, so I guess we should create a separate issue for this too.

_Originally posted by @svili in https://github.com/ec-doris/kohesio-frontend/issues/548#issuecomment-1160156871_

**Comment by madewild** [comment]
@svili what's the status on these leftovers?

**Comment by svili** [comment]
The kronjob is working, you said you just added the managing authorities to Italy and there is no decision on the new subdomain for the data.

**Comment by madewild** [comment]
@svili let's review this

**Comment by madewild** [comment]
Fixed
