### ISSUE TITLE
Link to programme leads to Kohesio Homepage

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#666]
https://kohesio.test.ec.europa.eu/en/#my-region

Valid for several (all?) Interreg projects

Link to programme (in the project fiche) leads to Kohesio Homepage

![Link Programme](https://user-images.githubusercontent.com/74774446/174756923-4b103342-e876-4c23-9e40-7dc4ac1347ca.png)

**Comment by madewild** [comment]
Indeed, and also we should not put a link behind n/a:
![nalink](https://user-images.githubusercontent.com/942488/174758470-98bbdcdc-3c9a-436e-87ac-a5fefc673c52.png)

**Comment by raphdom** [comment]
can you test it, please, dev and test envs

**Comment by madewild** [comment]
Looks good to me.
@gachpas can you confirm and close?

**Comment by gachpas** [comment]
Hello @raphdom and @madewild , not sure what you ask me to check exactly?
Indeed the n/a does not offer link anymore....good.
However the Programme link does not offer link either...so we do not have that info? If it is the case, then yes, it can be close ;)

**Comment by madewild** [comment]
Well it does, https://kohesio.test.ec.europa.eu/en/projects/Q100952 for instance has a working program link.
But for some like https://kohesio.test.ec.europa.eu/en/projects/Q4298599 (which you mentioned above) we do not have the information: there is no URL on https://linkedopendata.eu/wiki/Item:Q2463550 (that's why we had a default link to the homepage, now removed).
@roberto-musmeci is this normal not to have a URL in the Wikibase for interreg programmes?

**Comment by gachpas** [comment]
@madewild , the info on programme (for which I reported a non-working link) seems existing: https://ec.europa.eu/regional_policy/de/atlas/programmes/2014-2020/spain/2014tc16rfcb006

How come we do not have that info?

**Comment by madewild** [comment]
Probably we did not import this for interreg projects... @D063520 @DiaZork do you know something?

**Comment by D063520** [comment]
Hi!

Yes, the information for this is missing in the graph:

https://linkedopendata.eu/wiki/Item:Q2463550

@roberto-musmeci can you provide it to us?

A csv with program name, homepage?

**Comment by roberto-musmeci** [comment]
it's done. it can be closed

**Comment by madewild** [comment]
I confirm it works on https://kohesio.development.ec.europa.eu/en/projects/Q4298599
