### ISSUE TITLE
Special filter for interreg projects

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#669]
more a question than an issue....

why is there no way to identify all Interreg projects via a filter on ETC?
Is there any meta-data allowing to do so?

**Comment by madewild** [comment]
I think we decided against giving them a special status... can change later if needed.

**Comment by madewild** [comment]
@D063520 to implement in backend first (projects API)

**Comment by madewild** [comment]
Implemented in the backend: https://github.com/ec-doris/kohesio-backend/issues/179

**Comment by raphdom** [comment]
done, can you test it, please? @roberto-musmeci @madewild

**Comment by madewild** [comment]
Works well on https://kohesio.development.ec.europa.eu/en/projects?nuts3=Arrondissement-of-Mons&sort=Total-Budget-(descending)&interreg=Yes for instance (in combination with NUTS filter).

However if I click on the 3rd result https://kohesio.development.ec.europa.eu/en/projects/Q4297390 I get a 404... @roberto-musmeci @D063520 did we delete some interref projects from the Wikibase which are still in the index?!

**Comment by raphdom** [comment]
this seems to be a problem in the dev index, because this is working fine:
https://linkedopendata.eu/entity/Q4297390
but not this:
https://kohesio.development.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q4297390

**Comment by raphdom** [comment]
Change the name to: PROGRAMME TYPE
Change the order to: before PROGRAMME filter
Values: Yes= Interreg, No=Investment in Growth and Jobs

**Comment by raphdom** [comment]
done, can you check, please? @roberto-musmeci @madewild

**Comment by madewild** [comment]
Looks good. We just need to keep in mind to improve the interaction between filters (e.g. programme and programme type) for next release...

**Comment by D063520** [comment]
Refresh of the URL is not working

**Comment by raphdom** [comment]
what do you mean?
https://kohesio.development.ec.europa.eu/en/projects?nuts3=Heidelberg&sort=Total-Budget-(descending)&interreg=Investment-in-Growth-and-Jobs
This works for me

**Comment by D063520** [comment]
ok, sorry ... probably I made some mistake
