### ISSUE TITLE
mailto buttons won't work with firefox & outlook on commission pc

### ISSUE THREAD

**Issue by Djang0** [ec-doris/kohesio-frontend#674]
Everything is in the title. From project view (same applies for e-mail button within social media button panel):
![image](https://user-images.githubusercontent.com/841633/174811669-9ff3cccb-a50e-44be-ae75-e6087502f959.png)
![image](https://user-images.githubusercontent.com/841633/174811720-e0605e37-978a-4bcf-ba17-492c1909910b.png)
![image](https://user-images.githubusercontent.com/841633/174811768-0f299aab-599c-4a89-a88a-facc2dcbf1d8.png)
![image](https://user-images.githubusercontent.com/841633/174811811-168c20f2-ddd2-460a-a086-c3d4545a8e10.png)

**Comment by madewild** [comment]
![report_issue](https://user-images.githubusercontent.com/942488/174824553-bea93291-a656-4a18-bf20-b3c2f4d08cda.png)
