### ISSUE TITLE
More and Graph buttons frame have disappeared

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio-frontend#679]
TEST
![image](https://user-images.githubusercontent.com/80402472/175341508-9f088b63-bfc9-4eba-827a-b4ebab9727a9.png)

PROD
![image](https://user-images.githubusercontent.com/80402472/175341627-3a5d284f-dc8f-4fc0-8189-ebb5b13a0c99.png)

**Comment by madewild** [comment]
For me it's fine on https://kohesio.test.ec.europa.eu/en/projects/Q100952
What browser do you use?

**Comment by AThollard** [comment]
This morning this is fine. Yesterday I was using Chrome, also this morning. Strange. Probably a temporary issue.
You can close it.
