### ISSUE TITLE
No map on project fiche

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio-frontend#680]
https://kohesio.test.ec.europa.eu/en/projects/Q3095626

**Comment by madewild** [comment]
I can see the map on this project:

![map](https://user-images.githubusercontent.com/942488/175478660-9cc5ae94-0d47-4096-8979-fa77d61b04d7.png)

Maybe it was a temporary issue?

**Comment by raphdom** [comment]
now is good, it was a problem with merge the frontend and backend not at the same time.
