### ISSUE TITLE
images not rendered in safari

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#681]
https://kohesio.test.ec.europa.eu/en/beneficiaries/Q276795

See below, image of ferrovie d'italia is not rendered

<img width="1728" alt="Screenshot 2022-06-23 at 22 32 07" src="https://user-images.githubusercontent.com/10883585/175394322-71c1431f-c5c4-4369-8d98-df5d70be191b.png">

**Comment by raphdom** [comment]
On my safari it is working fine, but we have a warning in the console:
"The page at https://kohesio.test.ec.europa.eu/en/beneficiaries/Q276795 was allowed to display insecure content from http://commons.wikimedia.org/wiki/Special:FilePath/Sede%20Centrale%20FS.jpg."

So the url of the image is still "http", this is more data issue, there is a way to detect all the image url and change it to https?

**Comment by madewild** [comment]
The correct url would be https://upload.wikimedia.org/wikipedia/commons/6/64/Sede_Centrale_FS.jpg

**Comment by D063520** [comment]
working on DEV
