### ISSUE TITLE
Acceptance environment unstable

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#684]

**Comment by madewild** [comment]
@svili there seems to be something unstable in ACC... for me it disappears when you press F12 but then it comes back...

**Comment by madewild** [comment]
Today I don't have the issue anymore...
@gachpas are you still experiencing strange behaviour in acceptance?

**Comment by gachpas** [comment]
Hello @svili and @madewild ,

well, it is much better today but still some issues (see pic attached) + issue to move the map with the mouse

**Comment by madewild** [comment]
and this problem is totally absent in TEST ??

**Comment by gachpas** [comment]
well, I have not experienced this when testing Kohesio in Test last time....and quickly checking now, I do not have it either...

although, I agree that the issue seems inconsistent, as the behaviour yesterday and today is different...

**Comment by madewild** [comment]
Mmmh, might be related to your connection or Gisco tiles that are slow... Difficult to debug, let's monitor it until Friday.

**Comment by madewild** [comment]
![carousel](https://user-images.githubusercontent.com/942488/176390488-f1fea766-a60f-45b1-8706-2a2013b8611f.png)

very strange and not reproducable every time...
@raphdom in case you have some time could you have a look at acceptance?

**Comment by gachpas** [comment]
@madewild ,
I have tried now and do not have any issue with map, nor carousel ;)
