### ISSUE TITLE
Add geocoordinates to beneficiaries csv export

### ISSUE THREAD

**Issue by bogdan-necula** [ec-doris/kohesio-frontend#685]
Dear Team

Do you plan to add location (city and country) to the beneficiaries csv export. In the URLs of the beneficiaries this information exists.

Thank you

**Comment by madewild** [comment]
Hello @bogdan-necula, the country is already in the name of each file so it seems a bit redundant... For the city, it could be done but the geo information is somewhat disparate: sometimes we have a string, sometimes a postal code, etc. Or would the latitude/longitude be useful? 

@D063520 what's your view on this?

**Comment by bogdan-necula** [comment]
Hi, lat-long would be great !

**Comment by D063520** [comment]
Hi,

as far as I know not all beneficiaries have a geo location. For sure not across all countries. To directly help you, you can extract this information yourself using this SPARQL endpoint:

https://query.linkedopendata.eu/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%23%20things%20of%20types%20beneficiaries%0A%20%20%3Fbeneficiary%20wdt%3AP35%20wd%3AQ196899%20.%0A%20%20%23%20beneficiaries%20in%20poland%0A%20%20%3Fbeneficiary%20wdt%3AP32%20wd%3AQ13%20.%0A%20%20%23%20beneficiaries%20with%20coordinates%0A%20%20%3Fbeneficiary%20wdt%3AP127%20%3Fcoordinates%20.%0A%7D%20limit%2010

- go to this link
-  execute the query
- press on "Download" -> "CSV" file

Does this already help you?

**Comment by D063520** [comment]
@bogdan-necula ping

**Comment by D063520** [comment]
Hi,

I just tried now and it seams to work:

https://query.linkedopendata.eu/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%23%20things%20of%20types%20beneficiaries%0A%20%20%3Fbeneficiary%20wdt%3AP35%20wd%3AQ196899%20.%0A%20%20%23%20beneficiaries%20in%20poland%0A%20%20%23%3Fbeneficiary%20wdt%3AP32%20wd%3AQ13%20.%0A%20%20%23%20beneficiaries%20with%20coordinates%0A%20%20%3Fbeneficiary%20wdt%3AP127%20%3Fcoordinates%20.%0A%7D

but I agree the query is a bit heavy which might cause the timeout

**Comment by bogdan-necula** [comment]
Thanks it did!

**Comment by D063520** [comment]
great! we will also try to add them to the exports for the next release, which should be in september. If you need any other data, try yourself over the endpoint or write us again : )

**Comment by madewild** [comment]
Checking this again, we only have 10.000 beneficiaries with geocoordinates out of 500.000... Seems to be a bit overkill to add this to the exports since it will be mostly empty. I will close it unless there is a big need to have it in the CSVs.
