### ISSUE TITLE
Carousel regression

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#686]
![carousel](https://user-images.githubusercontent.com/942488/176390488-f1fea766-a60f-45b1-8706-2a2013b8611f.png)

very strange and not reproducable every time...
@raphdom in case you have some time could you have a look at acceptance?

_Originally posted by @madewild in https://github.com/ec-doris/kohesio-frontend/issues/684#issuecomment-1169689054_

**Comment by madewild** [comment]
Also happens in prod although we did not touch it!

**Comment by madewild** [comment]
@svili and @omar0z tried to fix it but to no avail... still happens in prod
@raphdom when you're back can you have a look? it seems that the page is loading and the dimensions are not properly computed...

**Comment by raphdom** [comment]
now is good on PROD

**Comment by raphdom** [comment]
@madewild can you check this, I think we can close it
