### ISSUE TITLE
Missing project ID when reporting an issue from overlay window

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#690]
if you want to report an issue from the po-up window of a project, the link in the email is generic and not related to the project.

While it works when opening completely the project page

**Comment by madewild** [comment]
Ah yes I'm not surprised because it's linked to the URL... @raphdom can fix this for 1.3 ;)

**Comment by raphdom** [comment]
Fixed, can you check please?

**Comment by raphdom** [comment]
@madewild and @gachpas  can you check this, I think we can close it

**Comment by madewild** [comment]
Mmmh seems not fixed in TEST for me...

**Comment by gachpas** [comment]
Hello @raphdom and @madewild , 

it seems working fine for me in test ;)

Thanks and kr,
Pascal

**Comment by madewild** [comment]
Not for me... @raphdom have you merged from DEV to TEST?

**Comment by raphdom** [comment]
Now is merged into test, can you test @madewild?

**Comment by madewild** [comment]
Great now! Just one thing: maybe this should open in another tab... when I click "report an issue" it opens Gmail in place of Kohesio in the same tab.

**Comment by gachpas** [comment]
For me it works ok, as it opens my Commission email in another app ;)

**Comment by raphdom** [comment]
@madewild, can you try again now (on dev) should open in a new tab
