### ISSUE TITLE
Expose keep.eu URL in project detail page API 

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-frontend#708]
Example
https://linkedopendata.eu/wiki/Item:Q4300675 
https://linkedopendata.eu/wiki/Property:P562941 

We'd like to implement a sort of read further about the project for Keep.eu projects
https://kohesio.development.ec.europa.eu/en/projects/Q100952

**Comment by raphdom** [comment]
done, can you check on dev, please? @roberto-musmeci 
The good example:
https://kohesio.development.ec.europa.eu/en/projects/Q4300675

**Comment by madewild** [comment]
I would put a different from from when we redirect to inforegion...

"Read more on keep.eu" ?

**Comment by raphdom** [comment]
done

**Comment by madewild** [comment]
@roberto-musmeci waiting for your validation to close
