### ISSUE TITLE
Heatmap - number of projects and intervention field

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-frontend#710]
it looks like the heatmap is not working properly when selecting a specific intervention field 

https://kohesio.development.ec.europa.eu/en/projects?interventionField=010&sort=Total-Budget-(descending)&tab=map

**Comment by raphdom** [comment]
done, problem with zeros in the log scale, now we ignore them...

**Comment by madewild** [comment]
Looks good now
