### ISSUE TITLE
Change the disclaimer in the map

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#711]
Change the disclaimer in the map to a popup like here:

https://ec.europa.eu/statistical-atlas/viewer/

Should be translated in all languages also

**Comment by raphdom** [comment]
Done, can you check @madewild and close it, please?

**Comment by madewild** [comment]
Perfect. We need to translate the word "Disclaimer" to 24 languages?

**Comment by raphdom** [comment]
Don't know, what do you think?

**Comment by madewild** [comment]
Probably better to include it in the Poetry second batch to be on the safe side...
