### ISSUE TITLE
Add fund website to project API

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#713]
On https://kohesio.development.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q100952 there is already "fundLabel":"European Regional Development Fund" but we would also need "fundWebsite":"https://ec.europa.eu/regional_policy/en/funding/erdf/". 

This information is already in the Wikibase (see https://linkedopendata.eu/wiki/Item:Q2504369) and can be retrieved through the P67 (official website) property.

Query with 3 Kohesio funds: https://query.linkedopendata.eu/#select%20%2a%20where%20%7B%0A%20%20%3Fs%20wdt%3AP35%20wd%3AQ2504365%20.%0A%20%20%3Fs%20rdfs%3Alabel%20%3Flabel%20.%20FILTER%28lang%28%3Flabel%29%3D%22en%22%29%0A%20%20%3Fs%20wdt%3AP67%20%3Fwebsite%20.%0A%7D

**Comment by raphdom** [comment]
This is also implemented. Can you check and close it? @madewild

**Comment by madewild** [comment]
Great
