### ISSUE TITLE
Display external content 

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-frontend#714]
We are starting enriching projects with links to tweets, videos etc. Managing authorities are also sending us some materials so other unit of REGIO

For instance this [tweet](https://twitter.com/ElisaFerreiraEC/status/1537118383652712448) refers to this [project](https://kohesio.ec.europa.eu/projects/Q3810843) 

Could we embed the tweet or a youtube video if the property is availalbe in the KG ?
Of course it would be for the next releases.

**Comment by raphdom** [comment]
Have been implemented, can you check if it is okay? @roberto-musmeci @madewild @D063520 

https://kohesio.development.ec.europa.eu/en/projects/Q3810843

The multilingual works also 😃

**Comment by D063520** [comment]
this is a nice one!

**Comment by roberto-musmeci** [comment]
Lovely @raphdom ! It's a great feature !
