### ISSUE TITLE
Descriptions disappeared in dev

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#717]
https://kohesio.development.ec.europa.eu/api/facet/eu/search/project?offset=0&limit=15 contains empty descriptions for all projects
compare with https://kohesio.test.ec.europa.eu/api/facet/eu/search/project?offset=0&limit=15 where it works properly

**Comment by raphdom** [comment]
I didn't change anything, normally the property that I render here is descriptions, and apparently is empty now...

**Comment by D063520** [comment]
thank you Raph, forgot that! is working again ...
