### ISSUE TITLE
Download button does not work

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-frontend#725]
The download button does not generate any reports

https://kohesio.ec.europa.eu/en/projects?keywords=solar%20energy&sort=Total-Budget-(descending)&interventionField=013

Also if you click on the link, the list of projects are only related to intervention 013. 

Bug already there in prod.

**Comment by raphdom** [comment]
Issue fixed, please can you test and close?

**Comment by madewild** [comment]
works for me, @gachpas can you check with the original reporter?

**Comment by roberto-musmeci** [comment]
FYI @madewild @gachpas 
I sent an email to the reporter. It works for me too.
