### ISSUE TITLE
Double space in carousel pagination

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#733]
On https://kohesio.ec.europa.eu/en/ there is a double space bewteen "1" and "of 3" in the carousel pagination.
I tried to fix it on https://kohesio.development.ec.europa.eu/en/ by moving the non-breaking space inside the "of " string (see https://github.com/ec-doris/kohesio-frontend/commit/e63cf0669136cbe676ffe6f6454a7d90c9952fa3), it works but it's a bad solution because it break the multilingual version. @raphdom can you find a better way?

**Comment by raphdom** [comment]
fixed

**Comment by raphdom** [comment]
can you check this and close it? @madewild
