### ISSUE TITLE
Improve REACT EU theme display

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#736]
On https://kohesio.ec.europa.eu/en/themes
New theme is shown in white on grayish background, difficult to read and we miss an icon

**Comment by madewild** [comment]
@roberto-musmeci is there an icon for REACT??
@raphdom let's put the same grey background as technical assistance

**Comment by roberto-musmeci** [comment]
@madewild I provided the icon to Raph some days ago :)

**Comment by madewild** [comment]
Yeah so I heard 😉

**Comment by raphdom** [comment]
The icon now is available, you can see in the themes page:
https://kohesio.development.ec.europa.eu/en/themes
