### ISSUE TITLE
Reorganise boxes on project detail page

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#737]
Project info, funding, programme...

**Comment by raphdom** [comment]
can you check if this is already the case?

**Comment by madewild** [comment]
@roberto-musmeci do we need to reorganise something?

**Comment by roberto-musmeci** [comment]
If we have time for this now, I would restructure as follows:

Project Info
- Start date
- End date
- Theme 
- Intervention field 
- Read further about the project 

Funding
- Fund
- Total Budget 
- Eu Contribution
- Read further about the fund 

Program 
- Programming period 
- Program 
- Managing Authority
- Read further about the Program 

Beneficiary 
- Beneficiary name

**Comment by raphdom** [comment]
Hey @roberto-musmeci 
Do you want to put the Theme and the Intervention Field inside the Project info?
Normally it is a list, that's why we have a specific block for those.

**Comment by roberto-musmeci** [comment]
You are right. 
Let's then just move the managing authorities information to the Funding block below 'program'.

**Comment by raphdom** [comment]
"Funding block" or "Program block"?

**Comment by raphdom** [comment]
done
