### ISSUE TITLE
Add tooltip on project/beneficiary pages boxes “Graph” and “More”

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#738]
I will provide the text

**Comment by raphdom** [comment]
We can postpone this @madewild? Or we need the text to send it to e-poetry

**Comment by madewild** [comment]
Sorry I forgot this...

Graph: Visualise as a network
More: Open in the EU Knowledge Graph

Still time to send to ePoetry? Else we postpone yes, not critical.

**Comment by raphdom** [comment]
okay, great, still on time for it, thank you

**Comment by raphdom** [comment]
Done, sending to translations, I will close
