### ISSUE TITLE
Outermost regions API

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#741]
Now, I have this json hardcoded on my side, can you give me an API to get this from the KG? Can you add the total project number, by region, it will be great.
Thanks
```
[{
        label: "Madeira",
        country: "Q18",
        countryLabel: "Portugal",
        id: "Q203"
    },{
        label: "Azores",
        country: "Q18",
        countryLabel: "Portugal",
        id: "Q204"
    },{
        label: "Canary Islands",
        country: "Q7",
        countryLabel: "Spain",
        id: "Q205"
    },{
        label: "Réunion",
        country: "Q20",
        countryLabel: "France",
        id: "Q206"
    },{
        label: "French Guiana",
        country: "Q20",
        countryLabel: "France",
        id: "Q201"
    },{
        label: "Guadeloupe Saint Martin",
        country: "Q20",
        countryLabel: "France",
        id: "Q2576740"
    },{
        label: "Martinique",
        country: "Q20",
        countryLabel: "France",
        id: "Q198"
    },{
        label: "Mayotte",
        country: "Q20",
        countryLabel: "France",
        id: "Q209"
    }]
```

**Comment by raphdom** [comment]
done, all the values from the outermost regions now come via API, 
It is difficult to add the total Number of the project in all outermost regions? This allow us to colorize the regions on the heat map.

**Comment by D063520** [comment]
uuuuu, this is a bit custom ..... I think we will not make it for this release ..... I would need to think how to do this conretely. We also do not have the numbers on the main map at the beginning ....

**Comment by raphdom** [comment]
no, it is only for the heat map, inside the projects page, but no worries, we can postponned it to next year. Thanks

**Comment by raphdom** [comment]
I am going to close this, because it is duplicate of #709
