### ISSUE TITLE
Add NUTS3 code to API

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#742]
On https://kohesio.development.ec.europa.eu/api/facet/eu/nuts3?language=en we don't have the NUTS3 code (e.g. FR01)
Would be good to add it since it's an expert filter

**Comment by madewild** [comment]
To add in front of the NUTS name in the filter dropdown, like "FR1 - Île de France"

**Comment by raphdom** [comment]
I do prefer that you concatenate this in the server side, as we have it for Fund and Programme...
