### ISSUE TITLE
"0 of + length" instead of "0 of 0" when search returns an empty result

### ISSUE THREAD

**Issue by faustusdotbe** [ec-doris/kohesio-frontend#744]
See screenshots for illustration. This happens both for projects and beneficiaries.

**DEV**, as of 2022/11/08: 
![image](https://user-images.githubusercontent.com/5579081/200520282-2bb03f87-de6b-4e71-8824-9642611a3054.png)

**PROD**, as of 2022/11/08: 
![image](https://user-images.githubusercontent.com/5579081/200520418-b32abd63-7e43-4261-8de2-20e9be430ccb.png)

**Comment by raphdom** [comment]
fixed
