### ISSUE TITLE
NUTS3 Filter Undefined before label

### ISSUE THREAD

**Issue by DiaZork** [ec-doris/kohesio-frontend#745]
There is this undefined before the label of the NUTS, 
If you can take a look on it @raphdom
 
<img width="702" alt="Capture d’écran 2022-11-08 à 15 27 19" src="https://user-images.githubusercontent.com/34543056/200590845-51565f12-4adb-4319-8d9c-e7112c9de173.png">

**Comment by raphdom** [comment]
fixed
