### ISSUE TITLE
Website not accessible with latest version of Safari

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#747]
the problem on my side is that the browser is stuck at loading ifframe_api

<img width="1728" alt="Screenshot 2022-11-09 at 10 36 12 (1)" src="https://user-images.githubusercontent.com/10883585/200802675-3a499c4d-0cd8-4882-b335-c9d444db9b6a.png">

Version 16.1 (18614.2.9.1.12)

**Comment by raphdom** [comment]
for me it works, I have exactly the same version:

<img width="1308" alt="Screenshot 2022-11-09 at 11 21 46" src="https://user-images.githubusercontent.com/5124917/200805114-bd331005-ef33-49e2-b572-cea7a30aa67e.png">

Can you try to access this: https://www.youtube.com/iframe_api

**Comment by D063520** [comment]
very strange .... yes I can access the link directly, but it never terminates in kohesio ....

**Comment by D063520** [comment]
let's wait for some days, hope it will go away by it's own ....

**Comment by D063520** [comment]
It's a Safari bug:

https://forums.macrumors.com/threads/safari-certain-websites-wont-load-after-ventura.2367614/
