### ISSUE TITLE
Gran Canaria label

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-frontend#749]
User in DG REGIO noted that 
_When you are checking the map of the Kohesio platform and you zoom in the Spanish Canaries, when you set your mouse on Gran Canaria it says Madrid instead of Gran Canaria._ 

I double checked and it's indeed the case. 
Could you take a look ?

**Comment by madewild** [comment]
Indeed was a mistake in the graph. Fixed: https://linkedopendata.eu/w/index.php?title=Item%3AQ238234&type=revision&diff=32660996&oldid=32613448
