### ISSUE TITLE
"Only use my keywords" in pages in some languages is badly displayed

### ISSUE THREAD

**Issue by faustusdotbe** [ec-doris/kohesio-frontend#754]
See image:

![image](https://user-images.githubusercontent.com/5579081/204499270-288e50eb-c5af-490e-b6ca-010c0ea6aaa2.png)

**Comment by madewild** [comment]
Maybe we could shorten it to "Mes mots-clés uniquement"?

**Comment by faustusdotbe** [comment]
Yep. I'm going through all languages to see if this is an issue across the board and will report back. We might need help from the translators on this.

**Comment by raphdom** [comment]
Maybe it will be better change the button to bellow the words.

**Comment by raphdom** [comment]
Something like this:
Screenshot 2022-11-29 at 11.12.18

**Comment by faustusdotbe** [comment]
Below is a breakdown. I am not too fond of having the button at the bottom, but aesthetics are personal and this seems like an easy/quick fix so why not.

| Language  | "Use my keywords" text | Problematic? Y/N |
| ------------- | ------------- | ------------- |
| bg  | Използване само на моите ключови думи  | Y | 
| es | Utilizar únicamente mis palabras clave | Y |
| cs  | NO SEARCH RESULTS | NO SEARCH RESULTS |
| da | Brug kun mine nøgleord | N |
| de | Ausschließlich meine Schlüsselbegriffe verwenden | Y |
| et | Kasuta ainult minu võtmesõnu | N |
| el | Να χρησιμοποιηθούν μόνον οι λέξεις-κλειδιά μου | Y | 
| en | Use my keywords only | N | 
| fr | Utiliser mes mots-clés uniquement | Y | 
| ga | Ná húsáid ach mo chuid eochairfhocal | Y | 
| hr | Koristi samo moje ključne riječi | N | 
| it | Utilizza solo le mie parole chiave | N | 
| lv | Izmantot tikai manus atslēgvārdus | N | 
| lt | Naudoti tik mano raktažodžius | N | 
| hu | Csak saját kulcsszavaim használata | N | 
| mt | Uża l-keywords tiegħi biss | N | 
| nl | Gebruik alleen mijn trefwoorden | N | 
| pl | Użyj tylko moich słów kluczowych | N | 
| pt | Utilize apenas as minhas palavras-chave | Y | 
| ro | A se utiliza doar cuvintele-cheie introduse de mine | Y | 
| sk | Použiť len moje kľúčové slová | N | 
| sl | Uporabi le moje ključne besede | N | 
| fi | Käytä vain omia avainsanojani | N | 
| sv | Använd endast mina sökord | N |

**Comment by raphdom** [comment]
for I've changed the button place, can you check and close it?

**Comment by faustusdotbe** [comment]
Looks good, thanks!
