### ISSUE TITLE
Implement SEO

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#757]
It would be nice (and important) to have kohesio appearing in google searching like:

- projects financed by the eu
- projects eu
- projects funded by eu
- how does the eu spend his money
- projects erdf
- projects esf
- projects (other funds)
- projects cohesion (probably not in the communication scope)
- projects italy eu (in general projects COUNTRY eu)

**Comment by raphdom** [comment]
SEO rules:

- keywords meta tag is useless → [https://ahrefs.com/blog/meta-keywords/](https://ahrefs.com/blog/meta-keywords/)

Title tag (for every page) (translated):

- Between 50-60 characters, end up with | Kohesio

Description tag (for every page) (translated):

- Between 150-160 characters
- Can be more than the description, useful information about the page

Use \<h1> in every page and try to keep the same as the <title> tag

Open graph tags:

\<meta property="og:site_name" content="" />
\<meta property="og:type" content="website" />
\<meta property="og:url" content="" />
\<meta property="og:title" content="" />
\<meta property="og:description" content="" />
\<meta property="og:image" content="" />
\<meta property="og:image:alt" content="" />

Robots (dev, test, acc)

- \<meta name="robots" content="none"> - To avoid index the page

**Comment by D063520** [comment]
Proposition after discussion for the description of projects:

Project funded by the EU in the FUND (FUND ACRONYM) from REGION, COUNTRY (translated to languages)

example:

Project funded by the EU in the European Regional Fund (ERDF) fund in Turin, Piedmont, Italy

**Comment by raphdom** [comment]
The SEO was implemented in all pages: Can you please check, using the following links:

Homepage:
**https://www.opengraph.xyz/url/https%3A%2F%2Fkohesio.test.ec.europa.eu%2Fen%2F**

About (static page):
**https://www.opengraph.xyz/url/https%3A%2F%2Fkohesio.test.ec.europa.eu%2Fen%2Fabout**

Projects page without parameter:
**https://www.opengraph.xyz/url/https%3A%2F%2Fkohesio.test.ec.europa.eu%2Fen%2Fprojects**

Projects page with parameters (country, region, fund):
**https://www.opengraph.xyz/url/https%3A%2F%2Fkohesio.test.ec.europa.eu%2Fen%2Fprojects%3Fcountry%3DPortugal%26fund%3DERDF---European-Regional-Development-Fund%26region%3DAlgarve**

Project detail page:
**https://www.opengraph.xyz/url/https%3A%2F%2Fkohesio.test.ec.europa.eu%2Fen%2Fprojects%2FQ114488**

Beneficiary detail page:
**https://www.opengraph.xyz/url/https%3A%2F%2Fkohesio.test.ec.europa.eu%2Fen%2Fbeneficiaries%2FQ2511258**

### COMMENTS:
- I think we should explore more the description field (all pages)
- I don't have the FUND ACRONYM on the project detail level
- The format of the "FUND ACRONYM" for the project list is: "ERDF-European-Regional-Development-Fund"

**Comment by roberto-musmeci** [comment]
> * I think we should explore more the description field (all pages) 

@raphdom, what do you mean ? 

> * I don't have the FUND ACRONYM on the project detail level
> * The format of the "FUND ACRONYM" for the project list is: "ERDF-European-Regional-Develop

@D063520 @DiaZork, could we check on the API and modify in case?

**Comment by roberto-musmeci** [comment]
Also , I checked in Italian the description was not fully translated. Is it intended for the time being @raphdom https://www.opengraph.xyz/url/https%3A%2F%2Fkohesio.test.ec.europa.eu%2Fit%2Fprogetti%2FQ114488

**Comment by roberto-musmeci** [comment]
Also couple of points from Alain

- To add some meta tags even if it's not the most important parameter for SEO
- To explore also the thematic approach for projects search and project detail pages
- To ask Google to index PROD and not to index DEV and TEST (the last two are currently being shown by google)

**Comment by raphdom** [comment]
> Also , I checked in Italian the description was not fully translated....

We do not have the translations yet, need to confirm in EN before send them to e-poetry.

> @raphdom, what do you mean ?

Exactly that, we need to change the API in order to have that info on my side to display properly...

> To add some meta tags even if it's not the most important parameter for SEO

Where exactly? In the static pages or generate like keywords for each project?

> To ask Google to index PROD and not to index DEV and TEST (the last two are currently being shown by google)

This point is already covered, except in PROD I put the parameter:
`<meta name="robots" content="none">`
That means no index for robots

**Comment by roberto-musmeci** [comment]
define priorities for title and description for the project research page @roberto-musmeci

**Comment by DiaZork** [comment]
So right now dev should be broken. And for the change I made:
You can find a parameter **funds** which is a list that contain fund that have this attribute:
- **website** the website of the fund
- **fullLabel** the id + label for example *"ESF - European Social Fund"*
- **id** the id *"ESF"*
- **label** the label *"European Social Fund"*
The ID is always the english one (I'm using the [P1583](https://linkedopendata.eu/prop/direct/P1583) not skos:altLabel so let me know if this need to change) and the label change with the language

**Comment by raphdom** [comment]
should be good now on the project detail page, thank you @DiaZork

**Comment by roberto-musmeci** [comment]
As suggested by Alain we can also take a theme-based approach for the SEO. 
For this we could use the intervention field but the label would be way too long for the url title.
So discussing with @raphdom we agreed to create a sort of Kohesio category that could help find and categories projects.

I created them and they are available [here](https://query.linkedopendata.eu/#SELECT%20%3Fid_level3%20%3Flabel_level3%20%3Fid_level2%20%3Flabel_level2%20%3Fid_level1%20%3Flabel_level1%0AWHERE%7B%0A%20%20%3Fid_level1%20wdt%3AP35%20wd%3AQ4555006%3B%0A%20%20%20%20%20wdt%3AP35%20wd%3AQ4555165.%0A%20%20OPTIONAL%7B%3Fid_level1%20wdt%3AP579319%20%3Fid_level2%7D.%0A%20%20OPTIONAL%7B%3Fid_level2%20wdt%3AP579319%20%3Fid_level3%7D.%0A%20%20%0A%20%20%3Fid_level1%20rdfs%3Alabel%20%3Flabel_level1.%0A%20%20%3Fid_level2%20rdfs%3Alabel%20%3Flabel_level2.%0A%20%20%3Fid_level3%20rdfs%3Alabel%20%3Flabel_level3.%0A%0A%20%20%7D)
Level 1 is the broader level, level 3 is the most granular one. 

@DiaZork, can we expose this in the API ? 
As it is linked to intervention field we could maybe expose it [here](https://kohesio.development.ec.europa.eu/api/facet/eu/categoriesOfIntervention?language=en)

**Comment by roberto-musmeci** [comment]
Batch sent to e-poetry. Reply waited for March 3

**Comment by roberto-musmeci** [comment]
Translations have been imported. See SPARQL [query](https://query.linkedopendata.eu/#SELECT%20%3Fp%20%28COUNT%28%3Flabel%29%20AS%20%3Ftotlabels%29%0A%0AWHERE%7B%0A%20%20%3Fp%20wdt%3AP35%20wd%3AQ4555006%3B%0A%20%20%20%20%20rdfs%3Alabel%20%3Flabel%0A%7D%20GROUP%20BY%20%3Fp%20)

@raphdom is there any task left to implement here ?

**Comment by raphdom** [comment]
Still don't see the translations here for example:
https://kohesio.development.ec.europa.eu/api/facet/eu/kohesio_categories?language=fr&interventionField=https://linkedopendata.eu/entity/Q200641

The english version works fine:

https://kohesio.development.ec.europa.eu/api/facet/eu/kohesio_categories?language=en&interventionField=https://linkedopendata.eu/entity/Q200641

Any idea @DiaZork?

**Comment by raphdom** [comment]
now, seems to be good, right @DiaZork? we can finally close it?
