### ISSUE TITLE
Filters interactions

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#777]
- Nuts3 depends on country and region
- ?

**Comment by raphdom** [comment]
@roberto-musmeci can you see what are the relationships that we need between filters? I did the first one and it is already on dev, can you check, please?

**Comment by roberto-musmeci** [comment]
@raphdom excellent. 
One thing: if you select a country, a region the list of NUTS 3 is adapted to the selection. If you then change the country, the region filter gets reset (correct) but the NUTS 3 proposes still the selection for the previous country/region selection. 

When we change country, we should reset the NUTS 3 menu.

**Comment by raphdom** [comment]
this is the case already, no? In which scenario the nuts3 didn't reset when you select the country? Maybe we still have something that I didn't cover...

**Comment by madewild** [comment]
The issue occurs when country + region are selected

**Comment by raphdom** [comment]
this now is working, can you check again, please?

**Comment by roberto-musmeci** [comment]
it works perfectly. Thanks @raphdom
