### ISSUE TITLE
in map API return also upper regions

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#778]
this is needed to display the bread crump

**Comment by D063520** [comment]
@raphdom can you check if you have all you need?

**Comment by raphdom** [comment]
Hello @D063520 and @DiaZork.
It is possible to add the label of the region itself and the label of the upper regions? using the language parameter btw...

Example:
https://kohesio.development.ec.europa.eu/api/facet/eu/search/project/map?granularityRegion=https://linkedopendata.eu/entity/Q3526&language=en

**Comment by DiaZork** [comment]
Yes i'll do that

**Comment by DiaZork** [comment]
I've pushed the change on dev, it will be up soon

**Comment by raphdom** [comment]
thank you

**Comment by raphdom** [comment]
this is good now @DiaZork but I have an error here:
https://kohesio.development.ec.europa.eu/api/facet/eu/search/project/map?language=en
Can you check, please?

**Comment by DiaZork** [comment]
It's fixed

**Comment by raphdom** [comment]
Now we can navigate in the homepage with the url change for each map region, I put like a breadcrumb on the url just to help users to easily identify, but the most important is the QID in the end
@roberto-musmeci and @madewild can you test please?

**Comment by roberto-musmeci** [comment]
links seem to work well thanks @raphdom. 
However, the project near me functionality does not work anymore.

**Comment by D063520** [comment]
this is nice! also for sharing a particular view .....

**Comment by madewild** [comment]
Very nice indeed!
@roberto-musmeci for the PNM it seems unrelated so I opened a separate issue https://github.com/ec-doris/kohesio-backend/issues/207

**Comment by raphdom** [comment]
now, is even better, you have the coordinate on the url:

https://kohesio.development.ec.europa.eu/en/?mapRegion=Portugal,Centro-region,Coimbra-Region,Q2556199&coords=-8.3211792431454,40.1552222#my-region

and some documentation about how to embed the map:

https://github.com/ec-doris/kohesio-frontend/blob/dev/docs/embbeded-map.md

**Comment by D063520** [comment]
wanted to propose that, but then I thought I might be too picky! Even better feature! ; )

**Comment by roberto-musmeci** [comment]
Hi guys. Can we close it ? :)
