### ISSUE TITLE
Map showing in the front of the language selection on project page

### ISSUE THREAD

**Issue by DiaZork** [ec-doris/kohesio-frontend#803]
when you are on a project page and you click to change the language the map stay in the front 

<img width="1728" alt="Capture d’écran 2023-03-10 à 11 58 51" src="https://user-images.githubusercontent.com/34543056/224300547-c011650a-ad77-4d67-94e4-88861d1b0f01.png">

**Comment by raphdom** [comment]
Thank you for the test,
It is fixed now, can you test on DEV and close it, please?
