### ISSUE TITLE
Some CSS issues on ipad

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#809]
### **Button "Explore More" is overlapping with text**
![Kohesio](https://user-images.githubusercontent.com/10883585/225253938-29d40321-3496-44d1-8aa9-3ebbf5326209.png)

### **Circles are ovals**
![Kohesio-1](https://user-images.githubusercontent.com/10883585/225254013-3be15a74-09df-477a-9bb1-28c08129fa97.png)

### **Relevant drop down squezed and missaligned**
![Projects co-funded by the EU](https://user-images.githubusercontent.com/10883585/225254130-0f67393c-f041-4d09-9536-79f3295eb2cd.png)

### **Drop down relevance cut**
![Beneficiaries](https://user-images.githubusercontent.com/10883585/225254240-248930f7-ce50-40ad-af6f-6069072bd2fd.png)

### **Right hand side of project cut**
![ΕΛΛΗΝΙΚΗ ΑΝΑΠΤΥΞΙΑΚΗ ΤΡΑΠΕΖΑ Α Ε   Kohesio](https://user-images.githubusercontent.com/10883585/225254333-43d75401-d977-4893-8f6a-b67a0aa991cc.png)

### **3 boxes not aligned**
![Kohesio-2](https://user-images.githubusercontent.com/10883585/225254417-d21d5162-e744-4f8e-9cb0-2ca4ef581811.png)

**Comment by raphdom** [comment]
Finally @gachpas. I've fixed most of the problematics on ipad and tablets in general...
Can you test it please, on TEST environment?
Thank you

**Comment by gachpas** [comment]
I will try to do this next week if OK for you, as quite busy this week ;)
