### ISSUE TITLE
Problem with filter interaction on page reload

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#814]
This was noticed by Roberto. To reproduce

1) open this link:

https://kohesio.ec.europa.eu/en/projects?country=Italy&region=Sicily&interreg=Investment-in-Growth-and-Jobs&sort=Total-Budget-(descending)

2) go on program facet

In this API call:

curl 'https://kohesio.development.ec.europa.eu/api/facet/eu/programs?country=https://linkedopendata.eu/entity/Q15&region=https://linkedopendata.eu/entity/Q2449&language=en' \
-X 'GET' \
-H 'Accept: application/json, text/plain, */*' \

the region is not set. On the other side if one goes to the page and sets the filter this is not the case.

**Comment by raphdom** [comment]
Should now be fixed on PROD, can you check please?

**Comment by raphdom** [comment]
closing this issue, that was already fixed
