### ISSUE TITLE
Issue map Asturias (ES)

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#819]
Subject: Kohesio issue

Hello Pascal and Ludovic,

during the Open Day we realized that there is a bug on the Kohesio map: clicking on Asturias does not lead to seeing the projects there.

Hope this helps!

Best,
Louisa

**Comment by raphdom** [comment]
Seems that is a problem in the frontend, to show the info, because the API is working fine:
https://kohesio.ec.europa.eu/api/facet/eu/search/project/map?granularityRegion=https://linkedopendata.eu/entity/Q1140&language=en

**Comment by raphdom** [comment]
Hello @gachpas 

Seems to be working now, can you test it on TEST environment please?

**Comment by gachpas** [comment]
Hi @raphdom , map on the homepage is working ok but the one in the project page (tab map) is not working yet.

**Comment by raphdom** [comment]
now is fine even on project page(tab map) thanks @gachpas

**Comment by gachpas** [comment]
@raphdom , Good now :)
Thx
