### ISSUE TITLE
Notifications for Professional Space

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#826]
We need to inform users after have a SUBMITTED version of a project change.
Need to discuss the better architecture to send emails, or notifications inside the app is enough?

**Comment by madewild** [comment]
Sending emails from a Commission email is tricky... Even eTranslation don't send emails, they just have internal notifications.

**Comment by raphdom** [comment]
This was implemented. The notification system via email and in-app.
