### ISSUE TITLE
Editing feature - Not able to submit

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#828]
![image](https://github.com/ec-doris/kohesio-frontend/assets/74774446/ce6a3f78-d67f-432a-b86f-3061b7847579)

I have made 3 changes one after the other with a save in between each change and without submitting.
Then I try to submit the last draft (which have all changes) and I am not able to submit (error message attached)

**Comment by raphdom** [comment]
It is fixed, Can you test now please?

**Comment by gachpas** [comment]
OK. Thanks :)
