### ISSUE TITLE
Map not loading with different language query string

### ISSUE THREAD

**Issue by svili** [ec-doris/kohesio-frontend#859]
Works: https://kohesio.ec.europa.eu/en/?mapRegion=Hungary,Budapest,Q2576842#my-region
Doesnt work: https://kohesio.ec.europa.eu/hu/?t%C3%A9rk%C3%A9pR%C3%A9gi%C3%B3=Hungary,Budapest,Q2576842
(in hungarian)

Error on console:
ERROR TypeError: Cannot read properties of null (reading 'split')
    at Et.updateQueryParam (main.f769230c7b959f67.js:3:38213)

**Comment by raphdom** [comment]
We don't have a translation for Budapest, very weird
https://linkedopendata.eu/wiki/Item:Q2576842

**Comment by DiaZork** [comment]
A fallback to the english label has been add if the wanted language is not there. It should fix the error.
https://kohesio.development.ec.europa.eu/hu/?t%C3%A9rk%C3%A9pR%C3%A9gi%C3%B3=Magyarorsz%C3%A1g,Budapest,Q2576842#t%C3%A9rs%C3%A9gem

**Comment by svili** [comment]
Fixed by: https://github.com/ec-doris/kohesio-backend/issues/230
