### ISSUE TITLE
Leave only one H1 on homepage

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#868]
Currently we have 4

**Comment by raphdom** [comment]
on dev, can you test?

**Comment by madewild** [comment]
Now there is no H1 heading at all on the homepage?
I think the recommendation was to have the text "Kohesio: discover EU projects in your region" (just above the tabs) as the only H1, but currently it's still a div with `class="ecl-site-header__site-name"`.
Can we make it an h1 while staying ECL-compliant?

**Comment by raphdom** [comment]
Done, now the h1 is the Kohesio title

**Comment by madewild** [comment]
I still don't see any H1s in dev, only H2s, but I trust you if you say it's fixed...
