### ISSUE TITLE
Role list sorting unstable

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#879]
On https://kohesio.acceptance.ec.europa.eu/en/users
Click Add User button
Select Role dropdown menu
Every few seconds, the list (Admin, Editor, Rewiewer, User) is reordered from A-Z to Z-A. Strange UX, should be from A to Z always.

**Comment by madewild** [comment]
same when editing an existing user and trying to change role

**Comment by raphdom** [comment]
This is fixed on dev and test already, will be bugfix on acc soon, thanks
