### ISSUE TITLE
Sorting arrows not working for edits

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#880]
![sorting](https://github.com/ec-doris/kohesio-frontend/assets/942488/579527b8-c5d8-4f1c-90b3-11ab80897f28)

When you click the sorting arrows left of "Created", nothing happens. I would expect the list of edits to be ordered by reverse date.

**Comment by raphdom** [comment]
There is already a issue for next release to implement the sort in all tables:
https://github.com/ec-doris/kohesio-frontend/issues/871

**Comment by madewild** [comment]
ok sorry ;)
