### ISSUE TITLE
Professional space - Translating to 24 languages?

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#881]
Currently the pro space is only in English.
Should we translate new strings (Edits Dashboard, Edits, Filters, Project, Latest Status, Created, History, etc.) to all 24 languages with ePoetry?

**Comment by madewild** [comment]
For instance on https://kohesio.acceptance.ec.europa.eu/fr/edits

**Comment by madewild** [comment]
Also My Profile etc. on https://kohesio.acceptance.ec.europa.eu/fr/users/profile

**Comment by roberto-musmeci** [comment]
We can include the full multilingual version in December if it is ok for you

**Comment by madewild** [comment]
I checked in French and it looks mostly good but some strings are still untranslated:

![mon_profil](https://github.com/ec-doris/kohesio-frontend/assets/942488/80fdc1db-35b1-4775-8351-1b23dfa7bc49)

**Comment by madewild** [comment]
![notif](https://github.com/ec-doris/kohesio-frontend/assets/942488/4e5a8f2a-d67a-4973-b808-2d5f7a3d8de0)

**Comment by raphdom** [comment]
Closing this, the first batch for Professional Space was done and now we have some missing translations that are described in a new issue:
https://github.com/ec-doris/kohesio-frontend/issues/929
