### ISSUE TITLE
Carousel: overlap of arrow over text

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#901]
![Screenshot from 2024-02-08 10-39-18](https://github.com/ec-doris/kohesio-frontend/assets/942488/f9151ad3-687b-4e82-963e-d9b3887287c4)

possible regression? left arrow of carousel prevents text readability on images 2 and 3

same on multiple languages, all good for first image of carousel

**Comment by raphdom** [comment]
I cannot reproduce this, maybe in a special situation, I can see in the right of the image it is the first image, non?

**Comment by madewild** [comment]
I have this all the time, on both computers... Very strange, we can debug together

**Comment by raphdom** [comment]
It was fixed on dev, can you check please?
https://kohesio.development.ec.europa.eu

**Comment by madewild** [comment]
Perfect, thx
