### ISSUE TITLE
Add fund and multiple CCIS in parameters for embedded map

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#912]
Add fund and multiple CCIS in parameters for embedded map

**Comment by raphdom** [comment]
@DiaZork can you add the filter(multiple CCI's) on backend side? for map endpoint only.
@ntorbev can you change the documentation of the embedded map also? docs/embbeded-map.md

**Comment by DiaZork** [comment]
@raphdom it's already on dev

**Comment by DiaZork** [comment]
So first i've fix a bug there was in the API
And the CCI field take a CCI not the URI of the program so for [Q2463051](https://linkedopendata.eu/entity/Q2463051) it's 2014BE05M9OP001
to use this URI you have to put it in the program field (that doesn't support multiple value, is it wanted ?)
And last find i don't think this way `?cci[0]=` is supported to give a list you just have to comma separate the value `?cci=value1,value2,etc` and only keep 1 value if you only need one

**Comment by raphdom** [comment]
@DiaZork 
Great, this is working fine: 
https://kohesio.development.ec.europa.eu/wikibase/facet/eu/search/project/map?cci=2014BE05M9OP001
But not this:
https://kohesio.development.ec.europa.eu/wikibase/facet/eu/search/project/map?cci=2014BE05M9OP001,2014BE05M9OP002
