### ISSUE TITLE
Change order names for readability

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#913]
Order Readability (descending) -> Readability
Order Readability (ascending) -> REMOVE
Order Readability (descending) -> Readability and Budget
Order Readabilty (ascending) -> REMOVE

**Comment by ntorbev** [comment]
you can test on dev @madewild

**Comment by madewild** [comment]
thanks @ntorbev ! in meetings all morning but will test asap

**Comment by madewild** [comment]
I have trouble opening https://kohesio.development.ec.europa.eu/en/projects, is it redeploying?

**Comment by madewild** [comment]
I cannot really test the sorting (too slow, because not cached?) but I see the two good labels. Just one thing: I suggested "Readability **and** Budget" instead of "Readability Budget"

**Comment by ntorbev** [comment]
good catch for that 'and'. My bad, should be fine now
