### ISSUE TITLE
Add a button to add all ccis at once

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#916]
Add a button to add all ccis at once

**Comment by madewild** [comment]
![image](https://github.com/ec-doris/kohesio-frontend/assets/942488/6090d109-35e8-416e-b21b-d0f8a038e641)

**Comment by madewild** [comment]
Thanks @ntorbev ! Further suggestions:

- the button could be hidden when no country is selected
- lowercase the word "all": "Add all CCIs"
- put it at the top right (or bottom left) to avoid confusion with the "Add" button already at the bottom right

Additional question for @roberto-musmeci : is it normal that all Interreg CCIs are in the list? For instance for Belgium I can select "2014TC16RFCB006 - Interreg V-A - Spain-France-Andorra (POCTEFA)"

**Comment by roberto-musmeci** [comment]
> Additional question for @roberto-musmeci : is it normal that all Interreg CCIs are in the list? For instance for Belgium I can select "2014TC16RFCB006 - Interreg V-A - Spain-France-Andorra (POCTEFA)"

@madewild well spotted. No it should not be the case. It should behave like the program filter in the project research page.

**Comment by madewild** [comment]
So this is an issue on the backend side @DiaZork ?

**Comment by raphdom** [comment]
Closing this, I have created the new issue: https://github.com/ec-doris/kohesio-backend/issues/250
