### ISSUE TITLE
Allow to add/invite a list of users

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#917]
Allow to add multiple users at once with the same CCI scope

**Comment by madewild** [comment]
@roberto-musmeci @Dgojsic we can now add multiple users separated by commas
Could you check in dev and report any issues to @ntorbev ? We will adapt the interface to reflect this change, but this will imply to retranslate the new strings to 24 languages...

**Comment by raphdom** [comment]
now is possible to add multiple users, I am closing this issue
