### ISSUE TITLE
Deleting intervention fields from the filter does not update the URL

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-frontend#921]
feedback from colleagues:

I encountered some problems when filtering projects after intervention field and the download as XLSX.
I [filtered projects](https://kohesio.ec.europa.eu/en/projects?country=Greece&sort=Total-Budget-(descending)&interventionField=074,075,091,092,093) after country (Greece) and intervention fields 074,075,091,092,093, which returns 6.198 project hits.
I tried removing some of the intervention fields from the filter, by clicking the Xs next to the item and clicking show results again, but this does not successfully trigger a refreshing of the result list.
Removing the respective number from the URL works though.

**Comment by madewild** [comment]
Indeed, good catch

for instance on https://kohesio.ec.europa.eu/en/projects?interventionField=001,002,003&sort=Total-Budget-(descending)

**Comment by madewild** [comment]
Seems fine to me, @roberto-musmeci can you cross check?

https://kohesio.development.ec.europa.eu/en/projects?country=Greece&sort=Total-Budget-(descending)&interventionField=074,075,091,092,093
