### ISSUE TITLE
Add all CCIs button produces null CCIs in invitation payload

### ISSUE THREAD

**Issue by svili** [ec-doris/kohesio-frontend#937]
On Acceptance, to reproduce:
On the "Add user" dialog:
1. Choose invitation
2. Role EDITOR or REVIEWER
3. Choose any country (tested with Cyprus, Finland and Croatia)
4. Add all CCIs button
5. Send

Return 400 error from BFF probably due to the payload having a list of nulls in the allowed_cci_qids list.

**Comment by madewild** [comment]
Indeed, on https://github.com/ec-doris/kohesio-frontend/issues/916 I wrote "the button could be hidden when no country is selected"

**Comment by svili** [comment]
Ah sorry, edited the issue, this happens when country is selected.

**Comment by madewild** [comment]
Ah sorry I see it's greyed out on ACC...
@svili did you select a country first?

**Comment by madewild** [comment]
(forget about my previous comments @ntorbev ;) )

**Comment by madewild** [comment]
@svili I just tested on ACC with Cyprus and I can see the correct list of CCIs added below the button...

**Comment by svili** [comment]
Yes, the UI shows it correctly but hitting SAVE is an error because the payload produced contains nulls.
![image](https://github.com/ec-doris/kohesio-frontend/assets/11196689/cbde48ed-749a-4c26-9427-ed97c9b600f0)

**Comment by madewild** [comment]
@svili can you please test since you found the bug in the first place?
