### ISSUE TITLE
Information popup for type in beneficiary page is not working

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-frontend#942]
In beneficiary list the "i" icon for type filter in advanced filters is not working when we click on it:

![Screenshot 2024-04-25 at 10 18 46](https://github.com/ec-doris/kohesio-frontend/assets/5124917/5b7023f6-9ed9-4309-b5b1-bcf863f67cd3)

**Comment by madewild** [comment]
I confirm it works on dev
